#!/usr/bin/env perl
use strict;
use warnings;
use Data::Dumper;


my $g = Geek->new( );
my %sm = $g->named_groups(
    day => '\d\d\d\d-\d\d-\d\d',
    hour => '\d\d\d\d-\d\d-\d\dT\d\d',
    job => '\w+',
    typenum => '\d+',
);

# 'set -o pipefail; mkdir -p %d && netflag --local --file="%f.FLAG" -cmd=\'' . $via_flag_cmd . '\'' . ( $compress ? " | $compress " : '' ). ' > %f.TMP && mv %f.TMP %f'	
my $res = "../RESULT/10";
$g->routes(
    {	target=>"$res/$sm{day}/google/3/url_groups_diff.gz",
	need =>{
	    url_groups => sub{ $g->days( from=>$+{day}, shift=>1, n=>-2 )->files("$res/\%F/google/3/url_groups.gz") },
	},
	cmd => sub{ sub{warn "what to do?"} },
    },
    {	target=>"../RESULT/10/$sm{day}/google/3/url_groups.gz",
	need=>{
	    # here sub return code:
	    dom_grNdays => sub{ map { "../RESULT/10/$+{day}/google/3/dom_gr${_}days.gz" } (1..7) },
	},
	cmd => sub{
	    sub{ warn "what to do?" }
	},
    
    },
#    {	target=>"$res/$sm{day}/google/3/(<?dom_grNdays>dom_gr\\ddays.gz)",
#	need => 
#    
#    },
#    { 	target=>"../RESULT/10/$sm{day}/google/3/sz_vars_30days.gz", 
#	need=>{ 
#	    bids => sub{
#		# в данном случае возвращается arrayref, в котором список строк - значит это список файлов
#		$g->days( from=>$+{day}, n=>-3 )->files( "../RESULT/10/\%F/google/3/bids.gz" );
#	    },
#	    total => sub{
#		$g->days( from=>$+{day}, n=>-3 )->files( "../RESULT/10/\%F/google/0/total.gz" );
#	    },
#	},
#	
#	# определенные пользователем переменные - ,желательно, в нижнем регистре, предопределенные - в верхнем.
#	cmd => sub{"I return: day:$+{day}, target:$+{TARGET}, total:'$+{total}', bids:'$+{bids}'"},
#	
#	cmd => sub{
#	    sub{ print Dumper \@_ },
#	    $+{TARGET}, "'$+{total}'", "'$+{bids}'"
#	},
#
#    },
    { 	target => "../RESULT/10/$sm{day}/google/3/bids.gz",
	need => {
		total => sub{ "../RESULT/10/$+{day}/google/3/total.gz" },
	    },
	cmd => sub{
	    "hello $+{TARGET}"
	},	
    },
#    {
#	target => "../RESULT/10/$sm{day}/google/3/total.gz",
#    },

);

#die Dumper $g;

my @wanted = ( 
    #"../RESULT/10/2014-10-02/google/3/sz_vars_30days.gz",
    #"../RESULT/10/2014-10-02/google/3/url_groups.gz", 
    "../RESULT/10/2014-10-02/google/3/url_groups_diff.gz",
);

my %testers = ( sizele20=>sub{-s $_ <= 0 and $_} );
my %matched = $g->match( recursive => 1 ,wanted=>\@wanted );
die Dumper \%matched;





#------------ Geek -----------
package Geek;
use Data::Dumper;
use Date::Calc;

sub new{
 my $pkg = shift or die "Package! Usage: Geek->new()";
 my %se = ();
 return bless \%se;
};

sub uniq{
 # give LIST  
 # Return uniqued LIST
 if ( ref $_[0] eq "Geek" ){
    shift;
 }
 my %rv = map {$_,$_} @_;
 return wantarray ? (values %rv) : [values %rv];
}


sub routes{
 my $se = shift;
 ref $se or die "First param must be a reference to Geek object";
 $se->{routes} = \@_;
 
 return $se;
}

sub match{
 # gives "wanted", returns "jobs"
 my $se = shift;
 ref $se eq "Geek" or die "First param must be a reference to Geek object"; 
 my %pa = @_;
 my %allowed = (wanted=>1, recursive=>1, testers=>1, );
 if ( my @bad_params = grep { !$allowed{$_} } keys %pa ){
    die "Bad params: @bad_params. Allowed: ".(join(", ", keys %allowed));
 }
 my $wanted = $pa{ wanted };
 my $recursive = $pa{recursive};
 my $testers = $pa{testers}||{}; # allow to set: testers=>{ proto1=>sub{ -s $_ > 20 }, } # and need_file like 'proto1://aa.gz' - will checked that sub
 my %recursive_wanted;
 my @matched_routes;
 if ( !$se->{routes} ){ die "routes is empty." }
 my %rv; 

 for my $r ( @{ $se->{routes}||[] } ){
    if ( my $re = $r->{target} ){
	for my $wanted_elem ( @$wanted ){ # level I
	    if ( $wanted_elem=~$re ){
		#$rv{ $wanted_elem }{ target } = $wanted_elem;
		if ( my $need = $r->{need} ){
		    if ( ref $need eq "HASH"){
			for my $type ( keys %$need ){
			    my $need_smf = $need->{$type};
			    if (ref $need_smf eq "CODE"){
				my @need_smf = $need_smf->();
				#$rv{ $re }{ $wanted_elem }{ need }{ $type } = \@need_smf;
				my %tested = map { $_, $se->test( $testers, $_) } @need_smf; 
				$rv{ $wanted_elem }{ need }{ $type } = { %tested };
				%recursive_wanted = ( %recursive_wanted, map {$_,1} map {split /\s+/ } grep {$_} values %tested );
				#warn Dumper { recursive_wanted=>\%recursive_wanted }; 
			    }
			}
		    }
		}
		
		if ( my $cmd = $r->{cmd} ){
		    my $re2; my $str2;
		    my %named_groups = ( TARGET=>[$wanted_elem], %{ $rv{ $wanted_elem }{ need }||{} } );
		    #die Dumper \%named_groups;
		    for my $name ( keys %named_groups ){
			my $value;
			if ( ref $named_groups{$name} eq "ARRAY" ){
			    $value = join(" ", @{ $named_groups{$name} } );
			}else{
			    $value = $named_groups{$name};
			}
			
			my $escaped = quotemeta $value;
			#$escaped=~s/([?])/\\$1/g;
			
			$re2.="-$name-(?<$name>$escaped)";
			$str2.="-$name-$value";
		    }
		    my $str1 = "$wanted_elem$str2";
		    my $re1 = qr/$re$re2/;
	    	    die "---NOT MATCHED $str1 to $re1---" if not "$str1"=~$re1;
		    my @job = $cmd->();
		    if ( !@job ){
			die "empty job returned.".Dumper( \$rv{ $wanted_elem } );
		    #}elsif (@job==1){
		    #	$target->{job} = $job[0];
		    }else{
			#$target->{job} = \@job;
			$rv{$wanted_elem}{ job } = \@job;
		    }
		}
	    }
	}
    }
 }
 
 if ($recursive){
    my %wanted = map {$_,1} @$wanted;
    for my $k ( keys %recursive_wanted ){
	delete $recursive_wanted{$k} if $wanted{$k};
    }
#    warn Dumper {rw=>\%recursive_wanted};
    my %recursive_matched = %recursive_wanted ? $se->match( %pa, wanted=>[keys %recursive_wanted] ) : ();
#    warn Dumper {rm=>\%recursive_matched};
    %rv = ( %rv, %recursive_matched );
 }
 return wantarray ? %rv : \%rv;
}

#sub escape{
# my $se = shift or die "SE!";
# my $str = shift or die "string!";
#}

sub test{
 # testing files
 my $se = shift or die "SE!";
 my %proto_testers = (
    default => sub { 
	# check any file for non-zero size, or *.gz files for 'size -gt 20'
	grep { my $size=-s||0; m/\.gz$/ ? $size > 20 : $size } $_ 
    },
#    empty => sub{
#	# expand *,?,[] e.t.c and check for ZERO size, or size -le 20 for *.gz
#	grep { my $size=-s; m/\.gz$/ ? $size <= 20 : $size==0 } <${_}>
#    },
    dfs => sub{ system("bash","-c","hadoop fs -ls $_ | grep $_") },
 ); 
 if ( ref $_[0] eq "HASH" ){
    %proto_testers = ( %proto_testers, %{ shift() } );
 }

 my @fnames = @_;
 my @rv;

 for my $name ( @fnames ){
    $name=~s|((\w+)\:\/\/)||;
    my $proto =$2||"default";
    my $tester_code = $proto_testers{ $proto } or warn "Not found tester code for proto '$proto'. File:'$name'";
    ref $tester_code eq "CODE" or die "Tester code must be a CODE ref ".Dumper(\%proto_testers);
    for ( $name ){
	push @rv, $name ? join( " ", &$tester_code) : undef;
    }
 }

 return wantarray ? @rv : join " ",@rv;
}

sub days{
 my $se = shift or die "First param must be a reference to Geek object";
 #ref $se eq "Geek" or die "First param must be a reference to Geek object";
 my %pa = @_;
 my %allow = (from=>1, to=>1, n=>1, shift=>1);
 if ( my @bad_pars = grep { !$allow{$_} } keys %pa ){
    die "Bad parameters: @bad_pars. Allowed only: ".(join ", ", keys %allow);
 }
 my @rv;
 my $shift = $pa{"shift"}||0;
 if ($pa{from} and $pa{n}){
    my $n = $pa{n};
    my ($y,$m,$d)=$pa{from}=~/(\d\d\d\d)-(\d\d)-(\d\d)/;
    $y and $m and $d or die "bad parameter from=$pa{from}";
    my @ii = $n>0 ? ((0+$shift)..($n+$shift)) : (($n+$shift)..(-1+$shift));
    for my $i ( @ii ){
	push @rv, [ Date::Calc::Add_Delta_Days($y,$m,$d, $i) ];
    }
 }
 @rv = map {sprintf("%d-%02d-%02d",@$_)} @rv;
 my $days = Geek::Days->new('days');
 $days->days(\@rv);
 return $days;
}


sub named_groups{
 ref shift or die "First param must be a reference to Geek object";
 my %pa = @_;
 my %rv;
 for my $name (keys %pa){
    my $v = $pa{$name};
    #$rv{ $name } = qr/(?<$name>$pa{$name})/; 
    $rv{ $name } = "(?<$name>$pa{$name})"; 
 }
 return wantarray ? %rv : \%rv;
}


#-----------------------------------------------------------------
package Geek::Days;
use base qw|Object::Accessor|;

sub files{
 my $se = shift or die "se!";
 my $tmpl = shift or die "tmpl!";
 my @rv;
 for my $d ( @{ $se->days() } ){
    my $file = $tmpl;
    $file=~s/\%F/$d/g;
    push @rv, $file;
 }
 if (wantarray){
    return @rv;
 }else{
    my $files = Geek::Files->new('files');
    $files->files(\@rv);
    return $files;
 }
}




1;
