#!/usr/bin/env perl
use strict;
use warnings;
use Data::Dumper;
use lib '/home/d.belyaev/bike';
use Geek qw/ :all /;
use Getopt::Long;

my @wanted;
my $need = 'todo';
my $any = 'max';
my $deep = 4;
my $show_targets;
my $dump_jobs;
my $force;
my $deb;
my $set="";
my $first_job;
my $desc;
my $norun;

GetOptions(
    'wanted=s' => \@wanted, # list wanted files
    'need=s' => \$need, # 'todo'|'all'
    'any=s' => \$any, # 'max'|'min'
    'deep=n' => \$deep, # recursion deep
    'show_targets' => \$show_targets, # print all 'target' keys from routes 
    'dump_jobs' => \$dump_jobs,
    'force' => \$force,
    'debug' => \$deb,
    'set=s' => \$set,
    'first_job' => \$first_job,
    'desc' => \$desc, # print descriptions
    'norun' => \$norun, # not run jobs (skip they)
) or die "Bad opt!";

@wanted = split /\s+/, join " ", @wanted;

my %pn = possible_need();
$pn{ $need } or die "Not allowed need='$need'. Allowed only: ".join(", ", keys %pn );

my %pa = possible_any();
$pa{ $any } or die "Not allowed any='$any'. Allowed only:".join(", ", keys %pa);

my $g = Geek->new( );
my %sm = $g->named_groups(
    day => '\d\d\d\d-\d\d-\d\d',
    hour => '\d\d\d\d-\d\d-\d\dT\d\d',
    job => '\w+',
    tn => '\d+', # typenum
);

my $res = "../RESULT/10";
my $traits_copy = "../RESULT/traits_copy";

sub Files($$){  } # Files($days,TMPL) - файлы за 30 дней назад включая текущий $+{day}. Для сокращения кода.
sub ExistsFilesMinimum($$$){
 # вычисляет и просит только имеющиеся файлы из перечисленных
 # введена как принятие неизбежности того, что некоторые файлы пересчитать не могу, приходится брать что есть
 my ($days, $tmpl, $minimum ) = @_;
 my @need = days(from=>$+{day}, n=>-$days, shift=>1 )->files($tmpl);
 my @exists = grep { $g->test($_) } @need;
 if ( @exists < $minimum ){
    return @need
 }else{
    return @exists
 }    
}

$g->routes(
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/sz_vars_30days.gz",
	desc {"кластеризация $_{day}/$_{job}/$sm{tn}"},
	need {
	    bids => sub{ Files(30, "$res/\%F/$+{job}/$+{tn}/bids.gz") },
	    views => sub{ Files(30, "$res/\%F/$+{job}/$+{tn}/views.gz") },
	    tn1_totals => sub{ Files(30, "$res/\%F/$+{job}/1/total.gz") },
	    sessions => sub{ Files(30, "$res/\%F/$+{job}/$+{tn}/sessions.gz") },
	    pzbt => sub{ Files(30, "$res/\%F/$+{job}/$+{tn}/pzbt.gz") },
	    traits30days => sub{ "$res/$+{day}/$+{job}/$+{tn}/traits30days.gz" },
	    dom_net => sub{ Files(30, "$res/%F/net_sites/0/dom_net.gz") }, # dom_net всегда - из net_sites/0
	    dom_gr =>sub{ "$res/$+{day}/$+{job}/$+{tn}/dom_gr.txt" },
	},
	cmd => sub{ "nothing"},
    },
    { 	target "$res/$sm{day}/$sm{job}/$sm{tn}/(?<basename>bids\.gz|views\.gz|sessions\.gz|pzbt\.gz|uidsz.gz)",
	need {
	    total => sub{ "$res/$+{day}/$+{job}/$+{tn}/total.gz" },
	    },
	perl { "hello $_{TARGET}. There must use hash for select real script because target is regexp" },	
    },
    { 	target "$res/$sm{day}/$sm{job}/$sm{tn}/traits30days.gz",
	need {
	    uidsz => sub{ ExistsFilesMinimum(30, "$res/%F/$+{job}/$+{tn}/uidsz.gz",20) }, 
	    predicted => sub { ExistsFilesMinimum(30, "$traits_copy/%F/predict_gr_v2.gz",20) },
	    predicted_add => sub { ExistsFilesMinimum(30, "$traits_copy/%F/predicted_add.gz",20) },
	    auditory => sub { ExistsFilesMinimum(30, "$traits_copy/%F/auditory.gz",20) },
	    ctr10gr => sub { ExistsFilesMinimum(30, "$traits_copy/%F/ctr10gr.gz",20) },
	    ctr11gr => sub { ExistsFilesMinimum(30, "$traits_copy/%F/ctr11gr.gz",20) },
	    },
	perl { "hello $_{TARGET}." },	
    },
    {	target "$res/$sm{day}/net_sites/0/dom_net.gz", # только .../net_sites/0/...
	need {
	    total => sub{ "$res/$+{day}/net_sites/0/total.gz" },
	},
	bash { qb "./35_DOM_NET %s deb", $_{day} },
	note { viatmp => 0, flag=>0 },
    },
    { 	target "$traits_copy/$sm{day}/(?<basename>predict_gr_v2.gz|predicted_add.gz|auditory.gz|ctr10gr.gz|ctr11gr.gz)",
	perl { "hello $_{TARGET}." },	
    },

#-----------URLS----------
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/url_groups_diff.gz",
	# need - требуется иметь:
	need {
	    url_groups => sub{ Files(2, "$res/\%F/$+{job}/$+{tn}/url_groups.gz") },
	},
#LANG=POSIX sort -T. -t\* -m -k1,1 -k2,2 <(zcat "$prev_src" | awk -v"OFS=*" '{print $0,"prev"}') <(zcat "$src" | awk -v"OFS=*" '{print $0,"curr"}') | ./27_diff

	bash { qb( qq( 
	    LANG=POSIX sort -T. -t\\* -m -k1,1 -k2,2 <\( 
		zcat %s | awk -v"OFS=*" '{print \$0,"prev"}'
		\) <\(
		zcat %s | awk -v"OFS=*" '{print \$0,"curr"}'
		\) | ./27_diff 
	    ), @{$_{url_groups_ARRAY}});
	    #print $cmd;
	    #netflag sub { system "bash", '-c', $cmd }, flag=>$_{TARGET}, viatmp=>$_{TARGET};
	},
    },
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/url_groups.gz",
	# any - способ указать, что требуется хотябы один из указанного списка:
	any {
	    # here sub return code:
	    dom_grNdays => sub{  map { "$res/$+{day}/$+{job}/$+{tn}/dom_gr${_}days.gz" } reverse (1..7) },
	},
	perl { warn "what to do?" },
    },
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/dom_gr(?<N>\\d)days.gz",
	# д.б х-м!
	need {
	    dom_gr => sub{ Files( $+{N}, "$res/\%F/$+{job}/$+{tn}/dom_gr.txt") }
	},     
	perl { warn "what to do again?" },    
    },
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/dom_gr.txt",
	any {
	    domsNNdays => sub{ map {"$res/$+{day}/$+{job}/$+{tn}/doms${_}days.gz"} reverse (10..30) },
	},
	perl {"aa"},
    },
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/doms(?<NN>\\d\\d)days.gz", 
	need {
	    urlsNNdays=>sub{ "$res/$+{day}/$+{job}/$+{tn}/urls$+{NN}days.gz" },
	},
	perl {"oy-oy"},
    },
    {	target "$res/$sm{day}/$sm{job}/$sm{tn}/urls(?<NN>\\d\\d)days.gz",
	need {
	    urls=>sub{ Files( $+{NN}, "$res/%F/$+{job}/$+{tn}/urls.gz") },
	},
	perl { print $_{day} },
    },
    {
	target "$res/$sm{day}/$sm{job}/$sm{tn}/urls.gz",
	need {
	    total=>sub{ "$res/$+{day}/$+{job}/$+{tn}/total.gz" }
	},
	perl {"sss"},
    },
    {
	target "$res/$sm{day}/$sm{job}/$sm{tn}/total.gz",
	need {
	    hours=>sub{ $g->hours( from=>$+{day}, n=>24, shift=>4 )->files("$res/$+{day}/$+{job}/$+{tn}/%FT%H.gz") }
	},
	perl {"merge"},
    },
    {
	target "$res/$sm{day}/$sm{job}/$sm{tn}/$sm{hour}.gz",
	perl {"hist"},
    
    },
    
    {
	target "../RESULT/TEST/$sm{day}/test.gz",
	need { aa=>sub{"aa"} },
	desc {"тестовый файл $_{day}"},
	bash { qb "sleep 10; echo $_{day} %s", qx(date) },
#	cmc => sub{},
    },
#    {
#	target "../RESULT/TEST/$sm{day}/test.gz",
#	need { bb=>sub{"bb"}},
#	desc {"тестовый файл - redefined $_{day}"},
#	bash { qb "sleep 10; echo $_{day} %s", qx(date) },
#	cmc => sub{},
#    }
    

);

if ($show_targets){
    local ($\,$,)=("\n","\n");
    print "Targets:", map {$_->{target}} $g->routes() and exit 0;
}


$\="\n";
my @jobs = $g->match( need=>$need ,any=>$any, deep=>$deep, wanted=>\@wanted );
if ( $dump_jobs ){	print Dumper \@jobs and exit 0  }	
my @jobs_to_do = $first_job ? $jobs[0] : @jobs;
for my $job ( @jobs_to_do ){
    my $file_exists = $g->test( $job->{target} ) ? "v" : "-";
    if ($desc){
	my @desc;
	push @desc, $job->{desc} ? $job->{desc} : "(without description)", " ($file_exists)";
	push @desc, "# $job->{job}" if !ref $job->{job};
	print join " ", @desc;
    }	
    
    next if $norun;
    
    my %defaults = (viatmp=>$job->{target}, flag=>$job->{target} );
    my %notes = %{ $job->{note}||{} };
    print join ",", map {"$_=$notes{$_}"} keys %notes if %notes and $deb;
    
    my ($rv, $msg) = netflag( 
	$job->{job},
	%defaults,
	%notes, 
	force=>$force, 
	deb=>$deb, 
	set=>$set, 
#	stdall=>"../RESULT/TEST/$job->{vars}{day}/test.log",
    );
    warn "Return value: $rv, msg=$msg" if $deb;
}    
    





