#!/usr/bin/env bash
#> Остановка всех скриптов.
#> Создается файл 01_STOP_ALL.stop, который перед запуском 01_START_ALL нужно удалить.
(
set -u
set -x
set -o pipefail
cd `dirname $0`
export PATH=$PATH:/usr/local/rle/var/share3/TIKETS/bike

echo "Stopped by $USER at $(date)" >> 01_STOP_ALL.stop

for i in `seq 1 10`; do

 ff=`find ../pids -name "*.pids"`
 for f in $ff; do 
    fork -pf=$f -kila -d; 
 done

done

)#>>"$0.log" 2>&1
