#!/usr/bin/env bash
#> Запуск всех скриптов.

export PATH=$PATH:/usr/local/rle/var/share3/TIKETS/bike:/usr/local/rle/bin
export PERL5LIB=/home/d.belyaev/perl5/lib/perl5:/usr/local/rle/lib/perl5/


set -u
set +x
set -o pipefail
cd `dirname $0`

[[ -s 01_STOP_ALL.stop ]] && echo "01_STOP_ALL.stop found! Remove it and try again.">&2 && exit 1

host=`hostname`

if [[ -s "$0.$host" ]]; then
    "$0.$host"
else
    echo "Not found script $0.$host">&2 && exit 1
fi        

