#!/usr/bin/env bash
#> Запуск всех скриптов.

export PATH=$PATH:/usr/local/rle/var/share3/TIKETS/bike:/usr/local/rle/bin
export PERL5LIB=/home/d.belyaev/perl5/lib/perl5:/usr/local/rle/lib/perl5/

(
set -u
set +x
set -o pipefail
cd `dirname $0`

[[ -s 01_STOP_ALL.stop ]] && echo "01_STOP_ALL.stop found! Remove it and try again.">&2 && exit 1


lo="6" # запуск только при loadaverage не больше lo или при "force"
mem=3 # need free mem

loadaverage -1m -gt "$lo" && echo "$(date +"%F %H:%M") loadaverage too big ($(loadaverage -1m))>$lo">&2 && exit
echo "Started at $(date +"%F %H:%M")" >&2 # debug for view log

# обновление 02_monit-human-view:
./02_human_view 02_monit.txt > 02_monit_human_view.txt

#----------------------- ежечасные -----------------------
for jobtn in `conf 00_conf.txt hours_jobtn`; do echo $jobtn; done | # f.e. net+0 net+1 ssp+0 ssp+1 ssp+3 ...
 while IFS=+ read job tn # f.e. job=net/ssp/google/mail tn=0/1/3
 do 
    loadaverage -1m -gt "$lo" && echo "$(date +"%F %H:%M") loadaverage too big ($(loadaverage -1m))>$lo">&2 && exit
    freemem -lt="$mem" -ed=g && echo "Low free memory. ( < $mem g)">&2 && exit

    hh=`hours -d=today -n=-3`

    cmd="nice ./10_HOURS_BY_HOURS "$job" "$tn" '$hh'"

    fork -pf=../pids/hours.pids -dela=10 -ed=s --single "$cmd" -wait
  
 done


)>>"$0.log" 2>&1