#!/usr/bin/env bash
#> Запуск всех скриптов.
(
set -u
set +x
set -o pipefail
cd `dirname $0`

[[ -s 01_STOP_ALL.stop ]] && echo "01_STOP_ALL.stop found! Remove it and try again.">&2 && exit 1

export PATH=$PATH:/home/d.belyaev/grep/bike

#jobs="google ssp_sites net-forty-three net-forty-four net-forty-five net-sixty"
jobs="google ssp_sites net_sites"
typenums="0 1 3"
for job in $jobs;do
    for typenum in $typenums; do
	# for any jobs and typenums:
	fork -pf="../pids/10.$job.t${typenum}.pids" -n=1 "nice -n20 ./10_HOURS $job $typenum"
	fork -pf="../pids/12.$job.t${typenum}.pids" -n=1 "nice ./12_MERGE $job $typenum"
    done

    # for any jobs:
    fork -pf="../pids/13.$job.pids" -n=1 "nice -n15 ./13_MERGE_30DAYS $job"
    fork -pf="../pids/14.$job.pids" -n=1 "nice -n15 ./14_BIDS $job" # несрочно
    fork -pf="../pids/15.$job.pids" -n=1 "nice -n15 ./15_SESSIONS $job" # несрочно
    fork -pf="../pids/16.$job.pids" -n=1  "nice -n15 ./16_PZBT $job" # несрочно

    fork -pf="../pids/17.$job.pids" -n=1  "nice -n15 ./17_URLS $job" # urls 

    fork -pf="../pids/18.$job.pids" -n=1  "nice -n15 ./18_UIDSZ $job" # несрочно
    fork -pf="../pids/19.$job.pids" -n=1  "nice -n15 ./19_URLS30DAYS $job" 
    fork -pf="../pids/20.$job.pids" -n=1  "nice -n15 ./20_DOM30DAYS $job" 
    fork -pf="../pids/21.$job.pids" -n=1  "nice -n15 ./21_DOMGR $job" 
    fork -pf="../pids/22.$job.pids" -n=1  "nice -n15 ./22_DOMGR7DAYS $job" 
    fork -pf="../pids/25.$job.pids" -n=1  "nice -n15 ./25_URLGR $job" 
    fork -pf="../pids/27.$job.pids" -n=1  "nice -n15 ./27_URLGR_DIFF $job"
    #fork -pf="../pids/29.$job.pids" -n=1  "nice -n15 ./29_JOIN $job" #(by sz, ad) # несрочно (нужно вообще ?)
    #fork -pf="../pids/30.$job.pids" -n=1  "nice -n15 ./30_SUM $job" # (by sz) # несрочно (нужно вообще?)

    fork -pf="../pids/32.$job.pids" -n=1  "nice -n15 ./32_COPY_TRAITS" 
    fork -pf="../pids/33.$job.pids" -n=1  "nice -n15 ./33_TRAITS $job" 
	
    fork -pf="../pids/51.$job.pids" -n=1  "nice -n15 ./51_SZVARS_30DAYS $job"
    fork -pf="../pids/55.$job.pids" -n=1  "nice -n15 ./55_SZGR $job"
done

# for once call:
fork -pf="../pids/95.pids" -single "nice ./95_REMOVE"

)#>>"$0.log" 2>&1
