#!/usr/bin/env bash
#> Остановка всех скриптов.
#> Создается файл 01_STOP_ALL.stop, который перед запуском 01_START_ALL нужно удалить.
(
set -u
set -x
set -o pipefail
cd `dirname $0`
export PATH=$PATH:/home/d.belyaev/grep/bike

echo "Stopped by $USER at $(date)" >> 01_STOP_ALL.stop

ff=`find ../pids -name "*.pids"`
for f in $ff; do 
    fork -pf=$f -kila -d; 
done

# когда кочается место на диске sort висит и не удаляет временные файлы. Такие файлы - признак того что висят просессы.
#tsff=`find . -name 'sort??????'`
#[[ -n "$tsff" ]] && echo "Removing temporary sort files: $tsff" && rm $tsff

)#>>"$0.log" 2>&1
