#!/usr/bin/env bash
#>
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?JOB!} # google | net-forty-three, ...
typenum=${2:?TYPENUM!} # 0|1|3

jobscript="./10_${job}_tn$typenum"
chk "$jobscript" "Job script" "-x" "exists and executable" noprint || exit 2


hours -t=2014-01-30T04 -n=24 |
files "../RESULT/10/%( hours -t=%f -n=-4 -first -day )/$job/$typenum/%FT%H.gz" |
only --without="total.gz" |
washing -time=10.time.log -v_flag="$jobscript %f $typenum" -comp=gzip


)>>"$0.log" 2>&1
