#!/usr/bin/env bash
#> Сбор часовых данных из hl за период 30 дней.
#> Параметры: $job и $typenum.

(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?JOB!} # google | net-forty-three, ...
typenum=${2:?TYPENUM!} # 0|1|3

#>: Каждой комбинации $job и $typenum соответствует свой скрипт сбора.  
jobscript="./10_${job}_tn$typenum"
chk "$jobscript" "Job script" "-x" "exists and executable" noprint || exit 2

#> Если присутствует total.gz то часовые данные не собираются.
#> Часы группируются в папки по суткам с 04.00 до 04.00.

hours -t=2014-02-14T04 -n=-30days -r |
files "../RESULT/10/%( hours -t=%f -n=-4 -first -day )/$job/$typenum/%FT%H.gz" |
only --without="total.gz" |
washing -time=10.time.log -v_flag="$jobscript %f" -comp=gzip


)>>"$0.log" 2>&1
