#!/usr/bin/env bash
#> сбор из hl typenum==0 (показы) , sid==187537 (google)

#>> отбрасываются нулевые sz,uid
#>> OUT: 
#>>  sz,ad,exposureprice,winprice
#>>  сортировка по sz, ad.

job_history_log "$1" "sz,ad,exposureprice,winprice,uid,typenum=0,sid=187537,statusnum=0" -fn -cut="sid,statusnum,typenum,uid" -true="sz,uid" |
sort -T. -t\* -n -k1,1 -k2,2

