#!/usr/bin/env bash
#> сбор из hl typenum==0 (показы) для группировки по урламs


set +x

sids=${2:?sids!} #like a: 123|234|3254

job_history_log -c=./history.conf "$1" "winprice,uid!=0,typenum=0,sid=$sids,sz,statusnum=0,usergroup=$(conf 00_conf.txt usergroups),ref" \
 -fn -cut="uid,typenum,sid,sz,statusnum,usergroup" -true="sz,ref" |
  perl -MDom -Mstrict -w -F'\*' -lane'
# IN: winprice,ref
#      0        1   
my ($dom,$ref) = $F[1] ? map {$_||""} Dom::split_ref( $F[1] ) : ("",""); # справа добавляется еще одна колонка

print join("*",map {$_||""} $dom, $ref, $F[0]);
' | LANG=POSIX sort -T. -t\* --compress-program=gzip -k1,1 -k2,2

