#!/usr/bin/env bash
#> history_log -------( jobscript )--------> ../RESULT/10/${day}/${job}/${typenum}/yyyy-mm-ddThh.gz
#>> Сбор часовых данных из hl.
#> Параметры: $job и $typenum.

(
set -u
set -x
set -o pipefail
cd `dirname $0`

job=${1:?JOB!} # google | net-forty-three, ...
typenum=${2:?TYPENUM!} # 0|1|3
day=${3:-""} # можно указать ОДИН day "yyyy-mm-dd"

# некоторые комбинации job+typenum не обрабатываются:
silent_exit=$( href -dict="
	net_sites => { 3=>'exit'},
    " -val="$job" -val="$typenum"
)
[[ -n "$silent_exit" ]] && exit 0

action=$( href -dict="
    ssp_sites => 'scp dm10.adriver.x:/work/data/share3/DATA/dicts/ssp_sites.txt ./ssp_sites.txt',
    net_sites => 'scp dm10.adriver.x:/work/data/share3/DATA/dicts/network_sites.txt ./network_sites.txt',
    " -val=$job 
)
[[ -n "$action" ]] && eval $action

sids=$( href -dict="
    ssp_sites=>\"` cat ssp_sites.txt | words -fu=sortnu -ot='|' `\",
    google=>187537,
    net_sites=>\"` cat network_sites.txt | words -fu=sortnu -ot='|' `\",
    " -val="$job"
)
chk "$sids" || exit 1


#>: Каждой комбинации $job и $typenum соответствует свой скрипт сбора.
jobscript="./10_${job}_tn${typenum}"

chk "$jobscript" "Job script" "-x" "exists and executable" noprint || exit 1

#> Если присутствует total.gz то часовые данные не собираются.
#> Часы группируются в папки по суткам с 04.00 до 04.00.

if [[ -n "$day" ]]; then
    hh=`hours -t="$day"T04 -n=24`
else
    #>: период, за который собрать данные (если их еще нет)
    period=`conf 00_conf.txt source_deep` 
    hh=`hours -t=todayT04 -n=-"$period"`
fi

echo "$hh" |
 files "../RESULT/10/%( hours -t=%f -n=-4 -first -day )/$job/$typenum/%FT%H.gz" |
 only --without="total.gz" |
 washing -time=10.time.log -cmd="$jobscript %f \"$sids\"" -comp=gzip 

)>>"$0.log" 2>&1
