#!/usr/bin/env bash
#> сбор из hl typenum==0 (показы) , sid for mail

#>> отбрасываются нулевые sz,uid
#>> OUT: 
#>>  sz,ad,exposureprice,winprice
#>>  сортировка по sz, ad.
set -u
set +x

hour_file=${1:? file!}

url_hour_file=`dirname $hour_file`"/url_"`basename $hour_file` # .../yyyy-mm-ddThh.gz --> .../url_yyyy-mm-ddThh.gz

sids=${2:?sids!} #like a: 123|234|3254

ads_file="adservice_domains.txt"



job_history_log -c=./history.conf "$hour_file" \
 "sz,ad,exposureprice,winprice,uid!=0,typenum=0,sid=$sids,statusnum=0,usergroup=$(conf 00_conf.txt usergroups),expid" \
 -fn -cut="sid,statusnum,typenum,uid,usergroup" | # sz,ad,expprice,winpr,expid
 tee-open -to "
 # ---- формирование url_YYYY-MM-DDTHH.gz (\$url_hour_file)
 # IN:
 #  1   2    3      4     5
 # sz, ad, exppr, winpr, expid
 awk -F* -vOFS=* '{print \$5,\$4}' | # выключил sort -t\\* -T. -k1,1n | # сортировка по expid ( не обязательна)
 viatmp -gz \"$url_hour_file\" 
 # OUT: 
 #   1     2
 # expid, winpr
 # <<-------- конец $url_hour_file  -------
 
 " | # это идет в файл $hour_file:
 awk -F* -vOFS=* '{print $1,$2,$3,$4}' | # (вычключил sz!=0, собираем с нулями) sz,ad,exppr,winpr
 sort -T. -t\* -n -k1,1 -k2,2 --compress-program=gzip
 

