#!/usr/bin/env bash
#> сбор из hl typenum==0 (показы) , network==60 

# если нужны будут exposureprice,winprice - то помнить, что winprice = (Winprice||(Secondprice/100_000))

# для сетевых сайтов, не сетевые показы - это как биды (проигранные?), сетевые показы - как биды(выигранные) и показы
# следовательно, этот сбор может включать в себя:

#>> OUT
#> [sid=LIST] (не выводится - будем запрашивать фильтрацию по списку sid'ов)
#>> uid - для сессий
#>> sec - для сессий
#>> sz
#>> pz - для комбинаций pzbt
#>> bt - для комбинаций pzbt
#>> exppr - для: среднего отношения к winprice, для доли бидов с положит ставкой( если не исп. ad для этого ) ( для выигранных бидов - сетевых просмотров), 
#>> winpr - для: среднего winprice, среднего отношения expprice к winprice ( для выигранных бидов - сетевых просмотров)
#>> ad - (влияет ли на положительную ставку?), для детализации по клиенту,  
#>> dom - для bids, sessions, urls
#>> path 
#>> metwork - (нужно ли фильтровать 43|44|45|60|0 ?) network=43|44|45|60|0 - показ сетевой (в какой сети) или нет

job_history_log "$1" "uid,second,sz,pz,bt,exposureprice,winprice,ad,ref,network,sid=${sids},typenum=0,statusnum=0"\
    -fn -cut="sid,typenum,statusnum" -true="uid" -fn -ll |
 lae -M=Dom '_{ $F[ REF ] = Dom::ref2dom( $F[ REF ] ); $F[ REF ]=~s/\.$//; p @F }' |
 LANG=POSIX sort -T. -t\* -k1,1 -k2,2n

