#!/usr/bin/env bash
#> сбор из hl typenum==0 (показы) , network==44 

# если нужны будут exposureprice,winprice - то помнить, что winprice = (Winprice||(Secondprice/100_000))

job_history_log "$1" "ref,ad,uid,network=44,typenum=0,statusnum=0" -fn -cut="uid,network,typenum,statusnum" -true="uid" -fn -ll |
lae -M=Dom '_{ $F[ REF ] = Dom::ref2dom( Ref ); $F[ REF ]=~s/\.$//; p @F }' |
LANG=POSIX sort -T. -t\* -k1,1 -k2,2n

#>> OUT:
#>> dom, ad
