#!/usr/bin/env bash
#> сбор из hl typenum==1 (клики) for net_sites

set +x

sids=${2:?sids!} #like a: 123|234|3254

job_history_log -c=./history.conf "$1" "sid=$sids,sz,ad,uid!=0,typenum=1,statusnum=0,usergroup=$(conf 00_conf.txt usergroups)" -fn \
 -cut="statusnum,typenum,uid,usergroup" -true="sz" |
sort -T. -t\* -n -k1,1 -k2,2 -k3,3
