#!/usr/bin/env bash
#> сбор из hl typenum==1 (клики) , network=60

#>> отбрасываются нулевые sz, uid.
#>> OUT: sz, ad
#>> сортировка: по sz,ad

job_history_log "$1" "sz,ad,uid,typenum=1,network=60,statusnum=0" -fn -cut="network,statusnum,typenum,uid" -true="sz,uid" |
sort -T. -t\* -n -k1,1 -k2,2
