#!/usr/bin/env bash


sids=${2:?sids!} #like a: 123|234|3254

job_history_log -c=./history.conf "$1" "uid!=0,second,sid=$sids,sz,pz,bt,exposureprice,ad,typenum=3,usergroup=$(conf 00_conf.txt usergroups),ref" -fn \
 -cut="typenum,usergroup" -true="sz" |
 ./10_url_clean -url_field=8 | #<--преобразование ref
 perl -MDom -Mstrict -w -F'\*' -lane'
# IN: uid,second,sid,sz,pz,bt,exposureprice,ad,ref
#      0    1     2  3  4  5       6        7   8

@F[ 8,9 ] = $F[8] ? map {$_||""} Dom::split_ref( $F[8] ) : ("",""); # справа добавляется еще одна колонка

print join("*", map {$_||""} @F);
' | sort -T. -t\* -n -k1,1 -k2,2 -S333M --compress-program=gzip


#>> OUT: uid second sid sz pz bt exposureprice ad dom path