#!/usr/bin/env bash


sids=${2:?sids!} #like a: 123|234|3254

job_history_log "$1" "uid,second,sid=$sids,sz,pz,bt,exposureprice,ad,typenum=3,statusnum=0,ref" -fn -cut="statusnum,typenum" -true="sz,uid" |
perl -MDom -Mstrict -w -F'\*' -lane'
# IN: uid,second,sid,sz,pz,bt,exposureprice,ad,ref
#      0    1     2  3  4  5       6        7   8

@F[ 8,9 ] = $F[8] ? map {$_||""} Dom::split_ref( $F[8] ) : ("",""); # справа добавляется еще одна колонка

print join("*",@F);
' | sort -T. -t\* -n -k1,1 -k2,2


#>> OUT: uid second sid sz pz bt exposureprice ad dom path