#!/usr/bin/env bash

sids=${2:?sids!} #like a: 123|234|3254

resf=${1:? resfile!}
teef=`dirname $resf`"/url_"`basename $resf` # .../yyyy-mm-ddThh.gz --> .../url_yyyy-mm-ddThh.gz

job_history_log -c=./history.conf "$1" "sid=$sids,sz,ad,exposureprice,winprice,uid!=0,typenum=0,statusnum=0,usergroup=$(conf 00_conf.txt usergroups),ref" -fn \
 -cut="statusnum,typenum,uid,usergroup" | # out: sid,sz,ad,expprice,winprice,ref
 tee-open -to "awk -F* -vOFS=* '{print \$6,\$4,\$5}' | LANG=POSIX sort -t\\* -T. --compress-program=gzip -k1,1 | viatmp -gz \"$teef\"" | # ref,expprice,winpr --> $teef
 awk -F* -vOFS=* '$2 {print $1,$2,$3,$4,$5}' | # <-- (sz!=0)  sid,sz,ad,expprice,winprice
 sort -T. -t\* -n -k1,1 -k2,2 -k3,3

