#!/usr/bin/env bash

# input from --tee-open (see 10_ssp_sites_tn0)

set +x

teef=${1:?teef!} # file to save result

awk -F* -vOFS=* '$6{print $6,$4,$5}' |
 ./10_url_clean --url_field=1 |
 lae -lb="ref +path exppr winpr" -M=Dom '
 _{ @F[REF,PATH] = Dom::split_ref(Ref); 
  p @F 
 }' |
 LANG=POSIX sort -t\* -T. --compress-program=gzip -k1,1 -k2,2 |
 summator -fu="+cnt,sum,sum" |
 viatmp -gz "$teef"
 
# out:  dom, path, cnt(exposures), sum(exppr), sum(winpr)
 
 