#!/usr/bin/env bash
#> Удаление часовых данных из tn3 (для экономии места)
#>> с задержкой в два дня (на случай захочется взглянуть на часовые данные).
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:? Job! }
typenum=${2:? Typenum! }

ff=`find ../RESULT/10/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum -type f -name "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9].gz" |
only -near=total.gz | only -older=2days`

[[ -n "$ff" ]] && rm $ff

)>>"$0.log" 2>&1
