#!/usr/bin/env bash
#> Удаление старых данных.


(
set -u
set +x
set -o pipefail
cd `dirname $0`

#>: параметр
job=${1:? Job! }
#>: параметр:
typenum=${2:? Typenum! }

#>> Удаление часовых данных, (в основном, для tn3) (для экономии места).
#>: на случай если захочется взглянуть на часовые данные, удаляем только старее чем:
hours_older="2days"

ff=`find ../RESULT/10/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum -type f -name "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9].gz" |
only -near=total.gz | only -older="$hours_older"`
[[ -n "$ff" ]] && rm $ff

#>: Удаление любых данных /RESULT/10/2014-01-18/$job/$typenum, старее указанного:
all_older="45days"

oldff=`find ../RESULT/10/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum -type d | only --older="$all_older"`
[[ -n "$oldff" ]] && rm -r $oldff

)>>"$0.log" 2>&1
