#!/usr/bin/env bash
#> Мержим часы в сутки, добавляем поля про сессии
(
set -u
set -x
set -o pipefail
cd `dirname $0`

job=${1:? Job! }
typenum=${2:? Typenum! }

find ../RESULT/10/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum -type f -name "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9].gz" |
only --without="total.gz" |
mergef -d -least=24 -m -k=1,1n -k=2,2n -k=3,3n -postfilter='./12_postf_'$job'_tn'$typenum' %totaldir/domains.txt'

)#>>"$0.log" 2>&1
