#!/usr/bin/env bash
#> Часы (YYYY-MM-HH.gz) ---------( через $posfilter )-----> $job/$tn/total.gz (в сутки)
(
set -u
set +x
set -o pipefail
cd `dirname $0`

#>:параметр:
job=${1:? Job! }
#>:параметр:
typenum=${2:? Typenum! }
#> days:
day=${3:-""} # можно указать day
deb=${4:-""} # млжно указать deb
[[ -n "$deb" ]] && set -x


# некоторые комбинации job+typenum не обрабатываются:
silent_exit=$( href -dict="
	net_sites => { 3=>'exit'},
    " -val="$job" -val="$typenum"
)
[[ -n "$silent_exit" ]] && exit 0

#>:Имя скрипта $postfilter зависит от $job и $typenum:
postfilter="./12_postf_${job}_tn${typenum}"
[[ -x "$postfilter" ]] || exit 3
#chk "$postfilter" "postfilter script" "-x" "exists and executable" noprint || exit 2

# Набор ключей для mergef тоже зависит от job и typenum:
mkeys=$( href -v="$job" -v="$typenum" -dict='
 "google" => 		{ 0 => "1,1n 2,2n", 1 => "1,1n 2,2n", 3 => "1,1n 2,2n" },
 "ssp_sites" =>		{ 0 => "1,1n 2,2n", 1 => "1,1n 2,2n", 3 => "1,1n 2,2n" },
 "net_sites" =>		{ 0 => "1,1n 2,2n", 1 => "1,1n 2,2n", },
' )
chk "$mkeys" "Ключи для mergef по $job и $typenum" || exit 1

#> не обрабатываются часовые данные, где рядом уже есть total.gz
#> не обрабатываются часовые данные с размером меньше или равно 20 байт
if [[ -n "$day" ]]; then
    find_path=../RESULT/10/$day/
else
    find_path=../RESULT/10/
fi

# допускается только 22 часа, тогда формируется ссылка с именем total.gz
# фильтр --without=total.gz не даст пересчитать total, если появился 24-й час
# это уберегает от разногласий в производных файлах - они все должны исходить из одной версии total.
# если нужно - таки пересчитать неполный total - удаляем существующий, при этом следить за производными данными. 

[[ ! -d "$find_path" ]] && exit 0

find "$find_path" -type f -wholename "*/$job/$typenum/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9].gz" |
 only --without="total.gz" |
 only -sizegt=20 |
 LANG=POSIX mergef -reverse -allow-empty -least=24 -having='m/T03/' --incomplete='22: %t_%n_hours.%e' -m -k="$mkeys" -postfilter="$postfilter" \
    -on_another="silent_skip" -timelog=00_all.time.log


)>>"$0.log" 2>&1

