#!/usr/bin/env bash
#> По урлам.
#> Обработчик смерженного (часы в сутки) потока для net_sites_tn0_url

#> из показов взяты только сетевые, разбивки на сети не делаем

#> для net_sites 0 url - есть prefilter, см выход с него

#          1     2      3          4               
# input: "dom  path  expprice secondprice" 

summator -fu="+cnt,sum,sum" | #<--- 1-dom  2-path  3-cnt  4-sum_expprice  5-sum_secondprice
 perl -F'\*' -lane'
 # округление десятичных:
 print join "*", @F[0..2], map { int($_) } @F[3,4]'

#>> OUT:
#>> | field            | decr |
#>> |----------------  | ---- |   
#>> | dom              |
#>> | path             |
#>> | cnt              |
#>> | sum_expprice     |
#>> | sum_secondprice  | сумма secondprice |
