#!/usr/bin/env bash
#> Обработчик смерженного (часы в сутки) потока для google tn3.

#>> Добавляем колонку про сессии: СЕКУНДЫ начала сессии КУКИ на ДОМЕНЕ, 
#>> и колонку "признак засчитываемого просмотра страницы" - незасчитываются повторные просмотры одной и тойже страницы с интервалом менее 10 сук.
#>> На входе поток за сутки (т.е период начало и конец которого можно считать разрывом сессии), лучше с 04-00 по 04-00.
#>> отсортрованный по КУКЕ и ВРЕМЕНИ. 

lae -lb="uid second sz pz bt exposureprice ad dom path +sestart +isview" '
my %sestart; 
my %last_view; 
my %prev_exp_sec;
_{

    
    if ( prevUid and Uid!=prevUid ){
	# uid was changed:
	undef %sestart;
	undef %last_view; 
	undef %prev_exp_sec;
    }

    
    if ( $prev_exp_sec{ &Dom } and ( Second - $prev_exp_sec{ &Dom } )>1800 ){
	# session timed out:
	$sestart{ &Dom } = 0;
	$prev_exp_sec{ &Dom } = 0; 
    }	
    
 
    # Если нет секунды начала на данном домене, значит началом сессии считаем текущую секунду:
    set_sestart( $sestart{ &Dom } ||= Second );
 
    # Просмотром считаем просмотр, если данный непустой referer не просматривался менее 10 сек назад:
    my $ref = join("",@F[DOM,PATH]);
    if ( $ref and ( 
		not exists $last_view{ $ref } 
		or (Second - $last_view{ $ref }) > 10 
    )){
	set_isview(1);
    }else{
	set_isview(0);
    }
 
    # Запоминаем, что и когда просматривала кука в последний раз:
    if ( $ref ){
	$last_view{ $ref } = Second
    }

 #>> OUT:
 #>>
 #>> | field | description |
 #>> | ----- | ----------- |
 #>> | uid   |
 #>> | sec   |
 #>> | sz    |
 #>> | pz    |
 #>> | bt    |
 #>> | exposure_price |
 #>> | ad      |
 #>> | domain  |
 #>> | path    |
 #>> | sestart | секунды начала сессии   |
 #>> | isview  | просмотр засчитан (1/0) |

 p @F;

 $prev_exp_sec{ &Dom } = Second; # храним время предыдущего просмотра любого реферера на домене
} -prev=>"uid=0";

'
