#!/usr/bin/env bash

#>>  1   2      3  4  5  6       7         8  9   10          
#>> uid second sid sz pz bt exposureprice ad dom path

awk -F* -v"OFS=*" '{print $9,$10,$7}' |
 LANG=POSIX sort -t\* -T. --compress-program=gzip -k1,1 -k2,2 |
 summator -fu="+cnt,sum,"
 
#>       1   2      3        4 
#> out: dom path bids(cnt) sum(expprice) 