#!/usr/bin/env bash


set -u
set -e
set -o pipefail
set +x

#>> IN:
#>>  1   2      3            
#>> dom path  winprice

summator -fu="cnt,+sum" 

#>> OUT: 
#>>  1   2     3            4 
#>> dom path cnt_exp   sum_winprice 

#>> | field        | description |
#>> | -----        | ----------- |
#>> | dom          |
#>> | path         |
#>> | cnt_exp      | количество показов |
#>> | sum_winprice | сумма winprice |



