#!/usr/bin/env bash


set -u
set -e
set -o pipefail
set +x

#>> IN:
#>>  1   2  3         4          5        
#>> sid sz  ad  exposureprice winprice

awk -F* -vOFS=* '{ print $0, ( $5>0 ? ($4/$5) : "NA" ) }' | # теперь стало 6 полей: sid, sz, ad, exposureprice, winprice, expprice/winprice' 
 summator -fu="+cnt,sum,sum,sum" 

#>> OUT: 
#>>  1   2  3     4              5               6           7
#>> sid sz  ad  cnt_exp  sum_exposureprice  sum_winprice sum_exp_div_win

#>>
#>> | field | description |
#>> | ----- | ----------- |
#>> | sid   |
#>> | sz    |
#>> | ad    |
#>> | cnt_exp | количество показов |
#>> | sum_exposureprice | сумма exposureprice |
#>> | sum_winprice | сумма winprice |
#>> | sum_expprice/winprice | сумма expprice/winprice |




