#!/usr/bin/env bash
#> По урлам.
#> Обработчик смерженного (часы в сутки) потока для net_sites tn0
#> net_sites tn0 - это показы, а также "биды" (сетевые показы - выигранные биды)

#> для net_sites 0 url - есть prefilter, см выход с него

#          1     2     3       4         5        
# input: "dom  path   net   expprice secondprice" 

summator -fu="+cnt,sum,sum" | #<--- 1-dom  2-path  3-net  4-cnt  5-sum_expprice  6-sum_secondprice
 perl -F'\*' -lane'
 # округление десятичных во всех полях:
 print join "*", @F[0..3], map { int($_) } @F[4,5]'

#>> OUT:
#>> | field            | decr |
#>> |----------------  | ---- |   
#>> | dom              |
#>> | path             |
#>> | net              |  
#>> | cnt              |
#>> | sum_expprice     |
#>> | sum_secondprice  | сумма secondprice |
