#!/usr/bin/env bash

#> Обработчик смерженного (за сутки) потока для net_sites tn1 (клики). 

set -u
set -e
set -o pipefail
set +x

#>> IN
#>>  1   2   3 
#>> sid  sz  ad

summator -la=0 -fu=+cnt

#>>OUT: 
#>>  1  2   3      4
#>> sid sz ad  cnt_clicks

#>> | field | description |
#>> | ----- | ----------- |
#>> | sid   |             |
#>> | sz    |
#>> | ad    |
#>> | cnt_clicks | количество кликов  |