#!/usr/bin/env bash

#> Обработчик смерженного (часы в сутки) потока для google tn1. 

set -u
set -e
set -o pipefail
set +x

#> IN
#>  1   2  
#> sz  ad

summator -la=0 -fu=+cnt

#>>OUT: 
#>>  1  2      3
#>> sz ad  cnt_clicks

#>> ,где
#>>   sz,ad - группировка
#>>   cnt_clicks - количество кликов в группе