#!/usr/bin/env bash
#>
(
set -u
set +x
set -o pipefail
cd `dirname $0`

deep=`conf 00_conf.txt report_deep`
job=${1:?JOB!}
days=${2:-"$(hours -t=today -shift=-1day -n=-$deep -days )"}

# скрипт выполняется только для перечисленных $job
todo=$( href -dict='
    "net-forty-three"=>1, "net-forty-four"=>1, "net-forty-five"=>1, "net-sixty"=>1
' -val=$job )

[[ -z "$todo" ]] && exit 0

for day in $days; do
    total_dir="../RESULT/10/$day/$job/0"
    total_f="$total_dir/total30days.gz"
    [[ -s "$total_f" ]] && continue
    
    need_files=$( hours -d=$day -shift=1day -n=-30days -days | files "../RESULT/10/%F/$job/0/total.gz" )
    if echo $need_files | only -all -sizegt=20 -noprint ; then
	
	mergef -ff="$need_files" -m -k=1,1 -k=2,2n -postf="summator -fu=sum" -gr="'$total_dir'" -tt="$total_f" -on_other_process="silent-skip"
	 
    else
	    #echo "Not found $? files: " >&2
	    #echo $need_files | only "[[ ! -s %f ]]" >&2
	continue    
    fi
done


)>>"$0.log" 2>&1
