#!/usr/bin/env bash
#> Удаление пустых файлов.
(
set -u
set +x
set -o pipefail
cd `dirname $0`

#>:параметр:
job=${1:? Job! }
#>:параметр:
typenum=${2:? Typenum! }

#> Удаление пустых данных ВСЕХ $job, когда gz-файлы ==20байт
emptyff=`find ../RESULT/10/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum -type f -name "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9].gz" |
only -sizele=20`
[[ -n "$emptyff" ]] && echo -e "Found empty files: $emptyff \n -will removed." && rm $emptyff

)>>"$0.log" 2>&1
