#!/usr/bin/env bash
#> total(tn3) ----( ./14_process )---> bids(tn3)
(
set -u
set +x
set -o pipefail
cd `dirname $0`

#>:параметр:
job=${1:?Job!} # google 
days=${2:-""}
deb=${3-""} # можно указать deb и читать лог

[[ -n "$deb" ]] && set -x

#> для разных $job разные источники:
typenum=$(
    href -dict="
	net_sites => '0',
    " -default="3" -value="$job"
)

#> script может отличаться для разных job:
scriptname=$(
    href -dict="
	net_sites => './14_process_net_sites'
    " -defa='./14_process_google' -val="$job"
)


if [[ -n "$days" ]]; then
	ff=`echo $days | files "../RESULT/10/%F/$job/$typenum/total.gz" | only -s`
else
	ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/total.gz" | sort | only --without="bids.gz"`
fi

    
echo "$ff" | washing -res="s|total.*?\.gz|bids.gz|" -v_flag="zcat %s | $scriptname" -comp=gzip -timelog="$0.time.log"

)>>"$0.log" 2>&1
