#!/usr/bin/env bash
#> Making table "bids" for net_sites (tn0).

#>> in (from tn0 total.gz):
# для net_sites биды - это все просмотры, сетевые и не сетевые

lae -lb="uid second sid sz pz bt exposureprice secondprice divexpsecond ad network dom path sestart isview" '
my ( %bids, %positive_bids, %dom );
_{
 $bids{ $F[SID] }{ $F[SZ] }{ $F[AD] }{ $F[EXPOSUREPRICE]>0||0 }{ ($F[NETWORK]||0) > 0 or 0 }++;
 $dom{ $F[SID] }{ $F[SZ] } ||= $F[DOM];
};

for my $sid ( sort {$a<=>$b} keys %bids ){
    for my $sz ( sort {$a<=>$b} keys %{$bids{$sid}} ){
	for my $ad ( sort {$a<=>$b} keys %{$bids{$sid}{$sz}} ){
	    for my $is_posibid ( sort {$a<=>$b} keys %{ $bids{$sid}{$sz}{$ad} } ){
		for my $is_network ( sort {$a<=>$b} keys %{ $bids{$sid}{$sz}{$ad}{$is_posibid} } ){
		    p0 $sid, $sz, $ad, $is_posibid, $is_network, $bids{ $sid }{ $sz }{ $ad }{ $is_posibid }{ $is_network }, $dom{$sid}{ $sz };
		}	
	    }
	}
    }
}
' 

#>> OUT="sz ad is_posibid is_network bids domain" # comment
#>> 
#>> | field  | description |
#>> | ------ | ----------- |
#>> | sid    |
#>> | sz     |
#>> | ad     |
#>> | is_posibid | ставки >0 |
#>> | is_network | сетевые показы (выинранные биды) |
#>> | bids   | количество бидов |
#>> | domain | домен (как внешний ключ для объединения с данными, сгруппированными по доменам ) |

#>> сортировака -n -k1,1 -k2,2 -k3,3 -k4,4

