#!/usr/bin/env bash
#> версия чистого перла N2

#> Making table "bids" (tn3).
#>> For ssp.
#>> in (from tn3 total.gz):
#>>  1   2      3   4  5  6        7       8   9    10   11    12      13 
#>> uid second sid  sz pz bt exposureprice ad expid dom path sestart isview


cut -d* -f3,4,8,10|
perl -w -F'\*' -lane'
# now input:
#       sid,     sz,     ad,      dom
$bids{ $F[0] }{ $F[1] }{ $F[2]||0 }++;
$dom{ $F[0] }{ $F[1] } ||= $F[3];

END{
 $,="*";
 for $sid ( keys %bids ){
    for $sz ( keys %{ $bids{$sid} } ){
        for $ad ( keys %{ $bids{$sid}{$sz} } ){
    	    print $sid, $sz, $ad, $bids{ $sid }{ $sz }{ $ad }, $dom{ $sid }{ $sz }||"";
        }
    }
 }    
}
' | sort -T. -t\* -S 333M -n -k1,1 -k2,2 -k3,3


#>> OUT: sz, ad, bids, domain.
#>> 
#>> | field  | description |
#>> | ------ | ----------- |
#>> | sid    |
#>> | sz     |
#>> | ad     |
#>> | bids   | количество бидов |
#>> | domain | домен (как внешний ключ для объединения с данными, сгруппированными по доменам ) |
#>>     Прим. 
#>>      Поле "количество бидов при exposureprice>0" (posibids) отсутствует, потому что
#>>      оно равно значению поля bids, за исключением случаев, когда ad=0. В этом случае оно равно 0.



