#!/usr/bin/env bash
#> Making table "sessions" (tn3).

#>> in:
#>> ожидаются поля: dom, uid, sestart
# входной формат дается в этом параметре:

lb=${1:?labels!}

fields_numbers=`perl -e'
 @F=split /\s+/, shift; 
 %L = map { $F[$_],$_+1 } (0..$#F); 
 print join ",", @L{qw| uid dom sestart isview |}' "$lb"`

cut -d* -f$fields_numbers |
lae -lb="uid dom sestart isview" '
# теперь на входе только три поля.
my ( %sessions, %views );
_{
  return if not Isview;

  $sessions{ &Dom }{ join("*", &Uid, &Sestart) }||=1;
  $views{ &Dom }++;
};

for my $dom ( keys %views ){
    p0 $dom, scalar(keys %{$sessions{ $dom }}), $views{ $dom };
}

'

#>> OUT: dom, sessions_count, views_count
#>> 
#>> | field          | description |
#>> | -------------- | ----------- |
#>> | dom            |
#>> | sessions_count |
#>> | views_count    |