#!/usr/bin/env bash
#> Making table "sessions" (tn3).

#>> in:
#>>  1   2     3   4  5       6        7   8   9     10      11
#>> uid second sz pz  bt exposureprice ad dom path sestart isview

lae -lb="uid second sz pz  bt exposureprice ad dom path sestart isview" '
my ( %sessions, %views );
_{
  return if not Isview;

  $sessions{ &Dom }{ join("*", &Uid, &Sestart) }||=1;
  $views{ &Dom }++;
};

for my $dom ( keys %views ){
    p0 $dom, scalar(keys %{$sessions{ $dom }}), $views{ $dom };
}

'

#>> OUT: dom, sessions_count, views_count
#>> 
#>> | field          | description |
#>> | -------------- | ----------- |
#>> | dom            |
#>> | sessions_count |
#>> | views_count    |