#!/usr/bin/env bash
#> total.gz (tn3)-----(./15_process)--->sessions.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

#>:параметр:
job=${1:?JOB!}

find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/3/total.gz" | sort -r |
only -without="sessions.gz" |
washing -res="s|total\.gz|sessions.gz|" -v_flag="zcat %s | ./15_process" -comp=gzip -time="$0.time.log"

)>>"$0.log" 2>&1
