#!/usr/bin/env bash
#> сочетания pz+bt

#> in:
#> sz,uid,second,pz,bt,exposureprice,ref,session,isview
#> 0   1    2    3  4       5         6    7       8

cut -d* -f1,4,5 |
perl -F'\*' -lane'
BEGIN{
 $,="*";
 $prevZs=0;
 
 sub flush{
    for $pz ( sort {$a<=>$b} keys %h ){
	for $bt ( sort {$a<=>$b} keys %{ $h{$pz} } ){
	    print $prevSz, $pz, $bt;
	}
    }
 undef %h;    
 }
 
}

flush() if $prevSz and $F[0]!=$prevSz;

$h{ $F[1] }{ $F[2] }=1;

$prevSz=$F[0];

END{ flush() }
'