#!/usr/bin/env bash
#> Сочетания pz+bt по sz.

#>> in:
#>>  1   2     3   4  5       6        7   8   9     10      11
#>> uid second sz pz  bt exposureprice ad dom path sestart isview

lb=${1:?labels!}

lae -lb="$lb" '
my %hash;
_{
 $hash{ $F[SZ] }{ $F[PZ] }{ $F[BT] }++;
};

for my $sz ( keys %hash ){
    for my $pz ( keys %{$hash{$sz}} ){
	for my $bt ( keys %{$hash{$sz}{$pz}} ){
	    p $sz, $pz, $bt, $hash{ $sz }{ $pz }{ $bt };
	}
    }
} 
' | sort -T. -t\* -S 333M -n -k1,1 -k2,2 -k3,3

#>> out:
#>>
#>> | field |
#>> | ----- |
#>> | sz    |
#>> | pz    |
#>> | bt    |
#>> | cnt ? | где используется (планировалось использовать ?) это поле? 
#>> оно является = количество строк из google tn3 total для sz+pz+bt
#>> т.е. количество бидов по sz+pz+bt