#!/usr/bin/env bash
#> total.gz (tn3) ----(./16_process)----> pzbt.gz

(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!} # google, ssp_sites
days=${2:-""}
deb=${3:-""}

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => '0',
 " -default="3" -val="$job"
)
      

if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/total.gz"`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/total.gz" | sort | only --without="pzbt.gz"`   
fi 

# у разных job форматы исходных total.gz могут быть разными:
lb=$(
 href -dict="
    net_sites => 'uid second sz pz bt exposureprice secondprice divexpsecond ad network dom path sestart isview',
 " -default='uid second sz pz  bt exposureprice ad dom path sestart isview' -val="$job"
)


echo "$ff" | washing -res="s|total\.gz|pzbt.gz|" -v_flag="zcat %s | ./16_process \"$lb\"" -comp=gzip -timelog="$0.time.log"


)>>"$0.log" 2>&1
