#!/usr/bin/env bash
#> Сочетания pz+bt по sz.

#>> in:
#>>  1   2     3   4  5       6        7   8   9     10      11
#>> uid second sz pz  bt exposureprice ad dom path sestart isview



cut -d* -f3,4,5 |
lae -lb="sz pz bt" '
my %hash;
_{
 $hash{ &Sz }{ &Pz }{ &Bt }++;
};

for my $sz ( keys %hash ){
    for my $pz ( keys %{$hash{$sz}} ){
	for my $bt ( keys %{$hash{$sz}{$pz}} ){
	    p $sz, $pz, $bt, $hash{ &Sz }{ &Pz }{ &Bt };
	}
    }
} 
' | sort -T. -t\* -S 333M -n -k1,1 -k2,2 -k3,3

#>> out:
#>>
#>> | field |
#>> | ----- |
#>> | sz    |
#>> | pz    |
#>> | bt    |
#>> | cnt   |