#!/usr/bin/env bash
#> urls.

#>>IN:
#>>  1   2     3   4  5       6        7   8   9     10      11
#>> uid second sz pz  bt exposureprice ad dom path sestart isview

#>> sorted by UID,SECOND:

awk -F* '$11' |
lae -lb="uid second sz pz  bt exposureprice ad dom path sestart isview" '
my %sessions_count;
my %sessions_ends;
my %urls;

_{
 #> when uid+sestart was changed:
 increment_counters() if ( Uid!=prevUid or Sestart!=prevSestart ) and prevUid and prevSestart;
 
 $urls{ join("*",Dom,Path||"") }||=1;

} -prev=>"uid=0,sestart=0,dom,path";

increment_counters();

sub increment_counters{
 #> sessions counters must be inremented:
 $_++ for @sessions_count{ keys %urls };
    
 #> sessions_end counter for last url must be incremented:
 $sessions_ends{ join("*",prevDom,prevPath||"") }++;
    
 undef %urls;
}

for my $ref ( keys %sessions_count ){
    # ( $ref - joined Dom*Path )
    p0 $ref, $sessions_count{ $ref }, $sessions_ends{ $ref };
}

' | LANG=POSIX sort -T. -S 333M -t\* -k1,1 -k2,2

#>>OUT:
#>> dom, ref, sessions_count, sessions_ends
#>>  
#>> | field          | description |
#>> | -------------- | ----------- |
#>> | sessions_count | количество сессий, где dom+url участвовал |
#>> | sessions_ends  | количество сессий, где он был последним.  |