#!/usr/bin/env bash
#> total.gz (tn3) ----(./17_process)----> urls.gz

(
set -u
set +x
set -o pipefail
cd `dirname $0`

#>:параметр:
job=${1:?Job!} # google
days=${2:-""} # можно указать day
deb=${3:-""} # можно указать deb

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => 0,
     google => 3,
     ssp_sites => 3
 " -val="$job"
)


if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/total.gz" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/total.gz" | only -s | sort -r | only --without="urls.gz"`
fi 

# у разных job форматы исходных total.gz могут быть разными:
lb=$(
 href -dict="
    net_sites => 'uid second sid sz pz bt exposureprice secondprice divexpsecond ad network dom path sestart isview',
    google    => 'uid second     sz pz bt exposureprice ad dom path sestart isview',
    ssp_sites => 'uid second sid sz pz bt exposureprice ad dom path sestart isview',
 " -val="$job"
)


maxf=`conf 00_conf.txt maxf`
echo "$ff" | washing -maxf="$maxf" -res="s|total\.gz|urls.gz|" -v_flag="zcat %s | ./17_process \"$lb\"" -comp=gzip -timelog="00_all.time.log"


)>>"$0.log" 2>&1
