#!/usr/bin/env bash
#> из total(tn3) ----> uidsz.gz ( Куки на сайтзонах. Сочетания uid+sz )
#>? Возможно потом придется переделать на "куки на sz+ad" , а из него уже делать куки на sz.(?)

(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!} # google
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net => '0',
     google => 3,
     mail => 3,
     ssp => 3,
 "  -val="$job"
)


if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/total.gz" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/total.gz" | sort -r | only --without="uidsz.gz"`   
fi

      
# у разных job форматы, и, следовательно, обработки могут быть разными:
process_cmd=$(
 href -dict="
    net => 'zcat %s | cut -d* -f1,3,4 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -k3,3 -u ', # у net format: uid,sec,sid,sz,... (sz - 4-е поле)
    ssp => 'zcat %s | cut -d* -f1,3,4 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -k3,3 -u ', # у ssp: uid,sec,sid,sz,...
    google =>    'zcat %s | cut -d* -f1,3 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -u ', # у google format: uid,sec,sz,...(sz - 3-е поле)
    mail =>      'zcat %s | cut -d* -f1,3 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -u ', # mail как google
 "   -val="$job" 
)

maxf=`conf 00_conf.txt maxf`    
echo "$ff" |
 washing -maxf="$maxf" -res="s|total\.gz|uidsz.gz|" -v_flag="$process_cmd" -comp=gzip -timelog="00_all.time.log"


#>>OUT:
#>> uid, [sid,] sz. (уникальные комбинации)
#>> сортировка по uid [sid,] и sz.

)>>"$0.log" 2>&1
