#!/usr/bin/env bash
#> из total(tn3) ----> uidsz.gz ( Куки на сайтзонах. Сочетания uid+sz )
#>? Возможно потом придется переделать на "куки на sz+ad" , а из него уже делать куки на sz.(?)

(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!} # google
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x

if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/3/total.gz" | only -s`
else
    ff=$(
	find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/3/total.gz" | sort |
	only --without="uidsz.gz"
	)
fi
    
echo "$ff" |
 washing -res="s|total\.gz|uidsz.gz|" -v_flag='zcat %s |awk -F* -v"OFS=*" "{print \$1,\$3}" | sort -T. -S333M -t\* -n -k1,1 -k2,2 -u ' -comp=gzip -timelog="$0.time.log"

#>>OUT:
#>> uid, sz. (уникальные комбинации)
#>> сортировка по uid и sz.

)>>"$0.log" 2>&1
