#!/usr/bin/env bash
#> из total ----> uidurl.gz ( Куки на урлах. Сочетания uid+url )

(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!} # google
day=${2:?"Day!"} # нужно  указать $day
deb=${3:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net => '0',
     google => 3,
     ssp => 3,
 "  -val="$job"
)


total="../RESULT/10/$day/$job/$typenum/total.gz"
chk "$total" "total file" "-s" "exists end noempty" nop || exit 1

urls_f="$(dirname "$total")/"

# у разных job форматы, и, следовательно, обработки могут быть разными:
process_cmd=$(
 href -dict="
    #net => 'zcat %s | cut -d* -f1,3,4 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -k3,3 -u ', # у net format: uid,sec,sid,sz,... (sz - 4-е поле)
    net => 'zcat %s | cut -d* -f1,12,13 | uniq |  sort -T. -S333M -t\* -n -k1,1 -k2,2 -k3,3 -u ', # у net format: uid,sec,sid,sz,... (sz - 4-е поле)
    zcat total.gz | cut -d* -f1,12,13 | grepf -fn <(zcat urls.gz) -fe='"$F1$F2"' -e='"$F2$F3"' | head
    #ssp => 'zcat %s | cut -d* -f1,3,4 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -k3,3 -u ', # у ssp: uid,sec,sid,sz,...
    #google =>    'zcat %s | cut -d* -f1,3 | uniq | sort -T. -S333M -t\* -n -k1,1 -k2,2 -u ', # у google format: uid,sec,sz,...(sz - 3-е поле)
 "   -val="$job" 
)

maxf=`conf 00_conf.txt maxf`    
echo "$ff" |
 washing -maxf="$maxf" -res="s|total\.gz|uidsz.gz|" -v_flag="$process_cmd" -comp=gzip -timelog="00_all.time.log"


#>>OUT:
#>> uid, [sid,] sz. (уникальные комбинации)
#>> сортировка по uid [sid,] и sz.

)>>"$0.log" 2>&1
