#!/usr/bin/env bash
#> urls30days.gz -----( удаляет поле path )----------> dom30days.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => '0',
 " -default="3" -val="$job"
)

minN=`froms 19_URLS30DAYS -var=minN -strict`
maxN=`froms 19_URLS30DAYS -var=maxN -strict`

possible_doms_names=`perl -e'
 ($min,$max)=@ARGV;
 print join " ", map {"doms${_}days.gz"} ($min..$max);
' "$minN" "$maxN"`

if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/urls[$minN..$maxN]days.gz" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/urls*days.gz" | sort -r |
     only --without="$possible_doms_names" |
     only --without="url_groups.gz"`
fi

      
echo "$ff" | washing -res='s|urls(\d+)days.gz|doms$1days.gz|' -v_flag="zcat %s | cut -d* -f1,3,4" -comp=gzip -timelog=00_all.time.log

)>>"$0.log" 2>&1
