#!/usr/bin/env bash
#> urls30days.gz -----( удаляет поле path )----------> dom30days.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => '0',
 " -default="3" -val="$job"
)

N=30

if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/urls${N}days.gz" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/urls${N}days.gz" | sort | only --without="doms${N}days.gz"`
fi

      
echo "$ff" | washing -res='s|urls(\d+)days.gz|doms$1days.gz|' -v_flag="zcat %s | cut -d* -f1,3,4" -comp=gzip -timelog=$0.time.log

)>>"$0.log" 2>&1
