#!/usr/bin/env bash
#> doms30days.gz -----( ...crawler job via ssh ...)---->dom_gr.txt , quant.gz
#> Запускать 1 поток!
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!} # google | ssp_sites | net_sites
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"
minN=`froms 19_URLS30DAYS -var=minN -strict`
maxN=`froms 19_URLS30DAYS -var=maxN -strict`

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => '0',
 " -default="3" -val="$job"
)


if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/doms[$minN..$maxN]days.gz" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/doms*days.gz" | sort -r | only --without="dom_gr.txt"`   
fi

      
server="crawler.adriver.x"
remote_project="/work/share/d.belyaev/1460_1421"
remote_script="1.sh"

echo "$ff" | washing \
    -res='s|doms\d+days\.gz|dom_gr.txt|' \
    -w="netflag --check --file=\"%f.FLAG\" -rm" \
    -r="( ! netflag --check --file=\"%f.FLAG\" -rm ) && [[ -e %f && ! -e %f.TMP ]]" \
    -do="set -o pipefail; mkdir -p %d && netflag --file=\"%f.FLAG\" -cmd=\"./21_process %s %f $server $remote_project $job $remote_script\"" \
    -time=00_all.time.log 

)>>"$0.log" 2>&1


