#!/usr/bin/env bash
#>
#(
set -u
set +x
set -o pipefail
cd `dirname $0`

# usage: ./21_process %s %f $server $remote_project $remote_script
local_src=${1:?Src!}
local_resf=${2:?Resf!}
server=${3:?Server!}
rem_project=${4:?Rem_proj!}
job=${5:?JOB!}
rem_script=${6:?Rem_script!}
day=`fn2days "$local_resf"`
rem_result="$rem_project/RESULT/10/$job/$day"
USER=d.belyaev

if ( ssh "${USER}@${server}" "mkdir -p $rem_result && [[ ! -s $rem_result/$( basename $local_src ) ]]" ) 
then
    scp -p "$local_src" "${USER}@${server}:$rem_result/"
fi    

if ( ssh "${USER}@${server}" "[[ -s $rem_result/dom_gr.txt && -s $rem_result/quant.txt ]] || $rem_project/bin/0.sh $rem_result/$(basename $local_src)" )
then
    scp "${USER}@${server}:$rem_result/*.txt" "$(dirname $local_resf)"
fi    

# clear old data on $server:
ssh "${USER}@${server}" "$rem_project/bin/90_clear"