#!/usr/bin/env bash
#> Dima's domain groups ------(./21_process)------->urs_groups.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
N=`froms 19_URLS30DAYS -var=N -strict`

r_filename="dom_gr.txt" #"test_groups.gz"

find ../RESULT/10 -wholename "*/$r_filename" | sort -r |
only -sizegt=20 |
words -first -comm="<-----ОтЛАДКА" |
washing -res="s|$r_filename|urs_groups.gz|" -v_flag="./22_process %s $job $N" -comp=gzip -time=$0.time.log

)>>"$0.log" 2>&1
