#!/usr/bin/env bash
set -u
set +x
set -o pipefail
cd `dirname $0`

#>: параметр (job), (здесь не используется)
job=${1:? Job! }
#>: параметр: имя файла-источника (current):
src=${2:? src file! }

#> из файла-источника получет день
day=`fn2days "$src"`
#> получает предыдущий день
prev_day=`days "$day" -n=-1`
#> получает имя (previous) файла-источника
prev_src=`echo "$src" | perl -lape'BEGIN{$prev=shift} s|\d\d\d\d-\d\d-\d\d|$prev|' "$prev_day"`
[[ ! -s "$prev_src" ]] && exit 3
#> previous + current --> пускает в один смерженный поток с добавлением последней колонки "curr"|"prev" и подает на вход ./23_diff
LANG=POSIX sort -T. -t\* -m -k1,1 -k2,2 <(zcat "$prev_src" | awk -v"OFS=*" '{print $0,"prev"}') <(zcat "$src" | awk -v"OFS=*" '{print $0,"curr"}') | ./23_diff
