#!/usr/bin/env bash
#> urls_groups.gz [вчера]+[сегодня] -----(23_process---23_diff)------> url_groups_diff.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}

src="url_groups.gz" 
result="url_groups_diff.gz"

find ../RESULT/10 -wholename "*/$job/3/$src" | sort -r | only -without="$result" |
 washing -result="s|$src|$result|" -v_flag="./23_process $job %s" -compr=gzip -timelog="$0.time.log" -nolog=3 -max=1


)>>"$0.log" 2>&1
