#!/usr/bin/env bash
#> dom_gr7days.gz ------(./25_process)------->url_groups.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
minN=`froms 19_URLS30DAYS -var=minN -strict`
maxN=`froms 19_URLS30DAYS -var=maxN -strict`
#src_filename="dom_gr7days.gz" 
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"
deep=`conf 00_conf.txt report_deep` # "<--- считать этот отчет на расчетные даты не старше report_deep из конфа"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => 0,
     google => 3,
     ssp_sites => 3,
 " -val="$job"
)


if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/dom_gr[1..7]days.gz" | only -sizegt=20`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/dom_gr*days.gz" | sort | only --without="url_groups.gz" |
	only -sizegt=20`   
fi

ff=$( echo "$ff" | only --upto="$deep" )

maxf=`conf 00_conf.txt maxf`
      
echo "$ff" |
washing -maxf="$maxf" -res="s|dom_gr\d+days.gz|url_groups.gz|" -v_flag="./25_process %s $job $typenum $minN $maxN" -comp=gzip -time=00_all.time.log

)>>"$0.log" 2>&1
