#!/usr/bin/env bash
#> urls_groups.gz [вчера]+[сегодня] -----(27_process---23_diff)------> url_groups_diff.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
src="url_groups.gz" 
result="url_groups_diff.gz"
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => '0',
 " -default="3" -val="$job"
)


if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/$src" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/$src" | sort | only --without="$result"`   
fi

echo "$ff" | washing -result="s|$src|$result|" -v_flag="./27_process $job %s" -compr=gzip -timelog="$0.time.log" -nolog=3

)>>"$0.log" 2>&1
