#!/usr/bin/env bash
#>
set -u
set +x
set -o pipefail

# на входе поток формата urls30days.gz
# doml * path * sess * sessends * bids
# 000a.ru*/a/add*3*1*6
# 000a.ru*/a/best/*1*1*3

awk -v n=10 -v m=300 -F* '
 pu!=$1 { out(); delete su; delete lu; s=0; l=0 }

 { pu=$1; s+=$3; l+=$4 } 
 
 $3>5 { su[$1""$2]=$3; lu[$1""$2]=$4 } 
 
 END{ out() } 
 
 function out(){
  if( s>100 && length(su)>0 ){
#    print pu "*" int(m*l/s) "*" length(su); 
    for( i in su ) 
	print i "*" int( m * (lu[i] + n * l/s) / (su[i] + n) )
  }
 }
' 

