#!/usr/bin/env bash
#>
(
set -u
set -x
set -o pipefail
cd `dirname $0`

job=${1:? Job! }
day=${2:? Day! }

tn=$(
 href -dict="
     net_sites => '0',
     google => 3,
     ssp_sites => 3,
 " -val="$job" 
)

src_f=`echo ../RESULT/10/$day/$job/$tn/urls30days.gz`
chk $src_f "source file for URL_CAT" "-s" "exists-and-noempty" nop || exit 2

echo "$src_f" | washing -res="s|urls30days\.gz|url_cat.gz|" -v_flag="zcat %s | ./28_process" -comp=gzip -time=00_all.time.log
)#>>"$0.log" 2>&1
