#!/usr/bin/env bash
#> $job/3/total + bids.gz + sessions.gz ------( 29_process )------> table29.gz
#> Объединение нескольких таблиц(файлов) в одну с группировкой по sz,ad.
#>> Печатаем по прежнему суммы, которые можно агрегировать за любой период.
#>> См. 29_process.
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}

find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/3/total.gz" | sort -r |
only -near="bids.gz sessions.gz" -comment='<----( рядом должны иметься все перечисленные файлы )' | 
only -having="s|/3/|/0/|" -comm='<----в папке /0/ тоже должен иметься total.gz' | 
only -having="s|/3/|/1/|" -comm='<----и в папке /1/ тоже' |
washing  -res="s|total\.gz|table29.gz|" -v_flag="./29_process %s $job"  -compr=gzip -timelog=$0.time.log

)>>"$0.log" 2>&1
