#!/usr/bin/env bash
#> Объединение сумм из отдельных: bids.gz, tn0/.../total.gz, tn1/.../total.gz, sessions.gz
#>  в одну таблицу по sz + ad.
#> Печатаем по-прежнему только суммы, которые можно агрегировать за период.
(
set -u
set -x
set -o pipefail
cd `dirname $0`

tn3_total_fn=${1:?src_file!} # tn3 total.gz
job=${2:?Job!}
day=`fn2days "$tn3_total_fn"`

tn0_total_fn="../RESULT/10/$day/$job/0/total.gz"
tn1_total_fn="../RESULT/10/$day/$job/1/total.gz"
tn3_bids_fn="../RESULT/10/$day/$job/3/bids.gz"
tn3_sessions_fn="../RESULT/10/$day/$job/3/sessions.gz"

# идем по bids.gz:
zcat "$tn3_bids_fn" | lae -M=Lae -lb="sz ad bids dom" '

my %tn0; # <-----exposures
for ( cat shift ){
    my ($sz, $ad, $exp, $winpr, $exppr) = split /\*/;
    $tn0{ $sz }{ $ad }={ exp=>$exp, winpr=>$winpr, exppr=>$exppr };
}
#die Dumper \%tn0;

my %tn1; # <-----clicks
for ( cat shift ){
    my ($sz, $ad, $cl) = split /\*/;
    $tn1{ $sz }{ $ad } = { cl=>$cl };
}

my %sessions;
for ( cat shift ){
    my ($dom, $sessions, $views) = split /\*/;
    $sessions{ $dom } = { sessions=>$sessions, views=>$views };
}

#die Dumper \%tn1;



_{

 #warn Dumper $tn0{ &Sz }{ &Ad };

 my $clicks=$tn1{ &Sz }{ &Ad }{ cl };
 my $exposures = $tn0{ &Sz }{ &Ad }{ exp };
 my $winpr = $tn0{ &Sz }{ &Ad }{ winpr };
 my $exppr = $tn0{ &Sz }{ &Ad }{ exppr };
 my $dom_sessions = $sessions{ &Dom }{ sessions };
 my $dom_views = $sessions{ &Dom }{ views };
 
 p0 Sz, Ad, $exposures, $clicks, Bids, $exppr, $winpr, $dom_sessions, $dom_views;

 #>>OUT:
 #>> Sz, Ad, $exposures, $clicks, Bids, $exppr, $winpr, $dom_sessions, $dom_views 
 #>> ,где sz, ad - группировка
 #>>  exposures - показов
 #>>  clicks - кликов
 #>>  bids - бидов всего (кол-во бидов при exposureprice>0 можно получить вычтя из bids те биды где поле ad=0)
 #>>  exppr - сумма exposureprice
 #>>  winpr - сумма winprice
 #>>  dom_sessions - количество сессий на домене
 #>>  dom_views - засчитанных посещений страниц кукой на домене (равно сумме длин сессий, где длина - количество просмотров неуникальных страниц)
}
' "$tn0_total_fn" "$tn1_total_fn" "$tn3_sessions_fn"

)#>>"$0.log" 2>&1
