#!/usr/bin/env bash
#> url_cat.gz [вчера]+[сегодня] -----(29_process---29_diff)------> url_cat_diff.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
src="url_cat.gz" 
result="url_cat_diff.gz"
days=${2:-""} # можно указать "$day1 $day2 ..."
deb=${3:-""} # можно указать "deb"
deep=`conf 00_conf.txt report_deep` # "<--- считать этот отчет на расчетные даты не старше report_deep из конфа"

[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
     net_sites => '0',
     google => '3',
 " -val="$job"
)


if [[ -n "$days" ]]; then
    ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/$src" | only -s`
else
    ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/$src" | sort -r | only --without="$result"`   
fi

ff=$( echo "$ff" | only --upto="$deep" )

maxf=`conf 00_conf.txt maxf`
echo "$ff" | washing -maxf="$maxf" -result="s|$src|$result|" -v_flag="./29_process $job %s" -compr=gzip -timelog="00_all.time.log" -nolog=3

)>>"$0.log" 2>&1
