#!/usr/bin/env bash
#> из сумм по sz, ad ---> суммы по sz 
#>> Добавляется колонка: количество бидов при ad!=0, равное кол-ву бидов где была положительная ставка
#>> сессии по домену суммировать нельзя, а нужно оставить одно (первое значение)

#>! поля domain в table29 нет, иду туда, добавлять... 

#>> in:
#>> Sz, Ad, $exposures, $clicks, Bids, $exppr, $winpr, dom,  $dom_sessions, $dom_views

lae -lb="sz ad exposures clicks bids exppr winpr dom dom_sessions dom_views" '
my ($exposures, $clicks, $bids, $positive_bids, $exppr, $winpr);
_{
 flush() if prevSz and Sz!=prevSz;

 $exposures+=Exposures;
 $clicks+=Clicks;
 $bids+=Bids;
 $positive_bids+=Bids if Ad>0;
 $exppr+=Exppr;
 $winpr+=Winpr;
 
} -prev=>"sz=0,dom,dom_sessions,dom_views";

flush();

sub flush{
 p0 prevSz, $exposures, $clicks, $bids, $positive_bids, $exppr, $winpr, prevDom, prevDom_sessions, prevDom_views ;
 $exposures= $clicks= $bids= $positive_bids= $exppr= $winpr= 0;
}
'

#>> OUT:
#>>  Sz, exposures, clicks, bids, positive_bids, exppr, winpr, Dom, Dom_sessions, Dom_views
#>>  ,где 
#>>    sz - сайтзона (группировка)
#>>    exposures - показов
#>>    clicks - кликов
#>>    bids - бидов всех
#>>    positive_bids - бидов при положительной ставке
#>>    exppr - exposureprice (ставка)
#>>    winpr - winprice
#>>    Dom - домен, которому принадлежит сайтзона 
#>>    Dom_sessions - сессий на домене
#>>    Dom_views - просмотров на домене (сумма длин сессий)