#!/usr/bin/env bash
#> table29 [т.е. суммы по sz и ad] ------( суммирование по sz )------> получаем table30.gz [суммы по sz]
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}

find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/3/table29.gz" | sort -r |
washing -res="s|table29\.gz|table30.gz|" -v_flag="zcat %s | ./30_process" -comp=gzip

#>> OUT:
#>>   Sz, exposures, clicks, bids, exppr, winpr, dom_sessions, dom_views
#>>   (аналогично table29 только суммы не по sz+ad а по sz).

)>>"$0.log" 2>&1
