#!/usr/bin/env bash
#> uidsz.gz (за {deep} дней ) + gender predicted_add ---------( ./32_process )-------> gender.gz
#>> Для каждого tn3 uidsz.gz: мержит за несколько (deep) дней такие же uidsz, включая текущий и объеденяет с gender predicted_add
#>> см ./32_process
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
traitsdir="/usr/local/rle/var/grep/d.belyaev/Traits"
deep=3 # Отладка. потом поставить =30 ( за сколько дней хотим мержить uidsz.gz )

# возьмем uidsz.gz:
ff=`find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/3/uidsz.gz" | sort -r | only -without="gender.gz"`
# только те, для которых есть predicted_add из gender:
replacement='s|../RESULT/10/(\d\d\d\d-\d\d-\d\d)/'$job'/3/uidsz.gz|'$traitsdir'/gender/RESULT/predicted_add.$1|'
ff=`echo "$ff" | only -having=$replacement`

ff=`echo $ff | words -first` # DEBUG

chk "$ff" "files"
echo "$ff" | washing -res="s|uidsz\.gz|gender.gz|" -v_flag="./32_process %s $job $deep $traitsdir" -d -comp=gzip 

)>>"$0.log" 2>&1
