#!/usr/bin/env bash
#> hist7 / traits files -----( copying ) ---> ../RESULT/traits_copy
(
set -u
set +x
set -o pipefail
cd `dirname $0`

# ----------- filled() function --------------------
filled () {
 # Is file $1 exists end it size > 20b ?
: ${1:? File! }
  echo "$1" | only -sizegt=20 -all -noprint
}
# ----------------------------------------

next_day_file () {
 # get filename with day in name
 # and N - delta days
 # return file for next day
 : ${1:? File! }
 : ${2:? N! }
 echo  "$1" | 
  perl -M'Date::Calc qw(Add_Delta_Days)' -e'
    $N = shift or die "N!";
    $N+=0 or die "not a digit!";
    chomp($_=<STDIN>);
    $re=qr|(\d\d\d\d)-(\d\d)-(\d\d)|; ($y,$m,$d)=m/$re/; $n=sprintf("%s-%02d-%02d",Add_Delta_Days($y,$m,$d,$N)); s/$re/$n/; print
 ' -- "$2"
}

days=${1:-""} # можно указать days

#report_deep="$(conf 00_conf.txt report_deep)" # за какие рассчетные дни (не старше чем)
source_deep="$(conf 00_conf.txt source_deep)" 

#report_first_day="$( hours -t=today -n=-"$report_deep" -days -first)"
#upto_day="$( hours -t="$report_first_day" -n=-"$source_deep" -days -first )"
upto_day="$( hours -t=today -n=-"$source_deep" -days -first )"

remote_host="hist7.adriver.x"

remote_gender_dir="/usr/local/rle/var/grep/"d.belyaev/Traits/gender/RESULT
remote_age_dir="/usr/local/rle/var/grep/"d.belyaev/Traits/age/RESULT
remote_kris_dir="/usr/local/rle/var/grep/"k.fedorenko/1126

local_dir="../RESULT/traits_copy"

# список дней, за которые желаем иметь локальные копии:
find_for_days=`hours -t=today -shift=1day -tod="$upto_day" -days`
[[ -z "$days" ]] && days="$find_for_days"


for day in $days; do
    # gender:
    # имена локальных копий немного меняем, приводя к какой-то системе имен:
    # gender - здесь txt-файлы копируются и потом сжимаются.
    remote_gender_file="$remote_gender_dir/predicted_add.$day"    
    local_gender_stem="$local_dir/$day/predicted_add" # ( full file name without any suffix )
    local_gender_file="$local_gender_stem.gz"

    if ! filled "$local_gender_file"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_gender_file ]]" && echo "OK" ) ]]; then
	    mkdir -p $(dirname "$local_gender_file") && \
	    scp "$remote_host":"$remote_gender_file" "$local_gender_stem.txt.COPYING.TMP"
	    mv "$local_gender_stem.txt.COPYING.TMP" "$local_gender_stem.txt" && \
	    cat "$local_gender_stem.txt" | viatmp -gz "$local_gender_file" && \
	    rm "$local_gender_stem.txt"
	    chk "$local_gender_file" "Copyed file" "-s" "was copyed" nop || exit 2
	else 
	    pref_day_file=$( next_day_file "$local_gender_file" -1 ) # файл предыдущего дня
	    pref_2day_file=$( next_day_file "$local_gender_file" -2 ) # файл пре-предыдущего дня
	    next_day_file=$( next_day_file "$local_gender_file" 1 ) # файл следующего дня
	    if filled "$pref_day_file" && filled "$next_day_file" ; then
		# копируем вчерашний файл в виде ссылки взамен ожидания текущего
		ln -s $(readlink -e "$pref_day_file") "$local_gender_file"
	    
	    elif filled "$pref_2day_file" && filled "$next_day_file" ; then
		# копируем позавчерашний файл в виде ссылки взамен ожидания текущего
		ln -s $(readlink -e "$pref_2day_file") "$local_gender_file"
	    fi
	    
	fi
    fi
    
    # age:
    remote_age_file="$remote_age_dir/$day/predict_gr_v2.gz"
    local_age_file="$local_dir/$day/predict_gr_v2.gz"

    if ! filled "$local_age_file"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_age_file ]]" && echo "OK" ) ]]; then
	    mkdir -p $(dirname "$local_age_file")
	    scp "$remote_host":"$remote_age_file" "$local_age_file.COPYING.TMP"
	    mv "$local_age_file.COPYING.TMP" "$local_age_file"
	    chk "$local_age_file" "Copyed file" "-s" "was copyed" nop || exit 2
	fi
    fi    

    # ctr10 (Kristina's groups):
    remote_kris_file_10="$remote_kris_dir/results/traits$day.gz"
    local_kris_file_10="$local_dir/$day/ctr10gr.gz"
    
    if ! filled "$local_kris_file_10"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_kris_file_10 ]]" && echo OK ) ]];then
	    mkdir -p $(dirname "$local_kris_file_10")
	    scp "$remote_host":"$remote_kris_file_10" "$local_kris_file_10.TMP" 
	    mv "$local_kris_file_10.TMP" "$local_kris_file_10"
	    chk "$local_kris_file_10" "Copyed file" "-s" "was copyed" nop || exit 2
	fi
    fi

#   inactiveUsers$day.gz больше нет    
    # ctr11 (Kristina's 11-th group):
#    remote_kris_file_11="$remote_kris_dir/inactiveUsers$day.gz"
#    local_kris_file_11="$local_dir/$day/ctr11gr.gz"
    
#    if ! filled "$local_kris_file_11"; then
#	if [[ $( ssh "$remote_host" "[[ -s $remote_kris_file_11 ]]" && echo OK ) ]];then
#	    mkdir -p $(dirname "$local_kris_file_11")
#	    scp "$remote_host":"$remote_kris_file_11" "$local_kris_file_11.TMP" 
#	    mv "$local_kris_file_11.TMP" "$local_kris_file_11"
#	    chk "$local_kris_file_11" "Copyed file" "-s" "was copyed" nop || exit 2
#	fi
#    fi

    # аудитории Ильи:
    # Файл один (без указания за какое число), поэтому за все дни пересчета копируется если еще не скопирован текущий файл
#    remote_host2="dm8.adriver.x"
    remote_file2="/usr/local/rle/var/share3/DATA/all_sites_10p_traffic/auditory.gz"
    if [[ ! -s $local_dir/$day/auditory.gz ]]; then
	# если он есть на удаленной стороне:
	#if [[ $( ssh "$remote_host2" "[[ -s $remote_file2 ]]" && echo OK ) ]];then 
	if [[ -s "$remote_file2" ]]; then
	    mkdir -p "$local_dir/$day/"
	    #scp "$remote_host2:$remote_file2" "$local_dir/$day/"
	    cp "$remote_file2" "$local_dir/$day/"
	    chk "$local_dir/$day/auditory.gz" "auditory file" '-s' 'was copyed' nop || exit 2
	fi
    fi

    # трейты buyers:
    # Файл один (без указания за какое число), поэтому за все дни пересчета копируется если еще не скопирован текущий файл
    remote_file3="/usr/local/rle/var/share3/DATA/traits/filtered_traits.txt.gz"
    if [[ ! -s $local_dir/$day/filtered_traits.txt.gz ]]; then
	# если он есть на удаленной стороне:
	if [[ -s "$remote_file3" ]]; then
	    mkdir -p "$local_dir/$day/"
	    cp "$remote_file3" "$local_dir/$day/"
	    chk "$local_dir/$day/filtered_traits.txt.gz" "buyers traits file" '-s' 'was copyed' nop || exit 2
	fi
    fi

	
    
done


)>>"$0.log" 2>&1
