#!/usr/bin/env bash
#> hist7 / traits files -----( copying ) ---> ../RESULT/traits_copy
(
set -u
set +x
set -o pipefail
cd `dirname $0`

# ----------- filled() function --------------------
filled () {
 # Is file $1 exists end it size > 20b ?
: ${1:? File! }
  echo "$1" | only -sizegt=20 -all -noprint
}
# ----------------------------------------

upto="$(conf 00_conf.txt report_deep)" # за какие рассчетные дни (не старше чем)
remote_host="hist7.adriver.x"

remote_gender_dir="/usr/local/rle/var/grep/"d.belyaev/Traits/gender/RESULT
remote_age_dir="/usr/local/rle/var/grep/"d.belyaev/Traits/age/RESULT
remote_kris_dir="/usr/local/rle/var/grep/"k.fedorenko/1126

local_dir="../RESULT/traits_copy"

# список дней, за которые желаем иметь локальные копии:
find_for_days=`hours -t=today -n=-"$upto" -days -r`

for day in $find_for_days; do
    # gender:
    # имена локальных копий немного меняем, приводя к какой-то системе имен:
    # gender - здесь txt-файлы копируются и потом сжимаются.
    remote_gender_file="$remote_gender_dir/predicted_add.$day"    
    local_gender_stem="$local_dir/$day/predicted_add" # ( full file name without any suffix )
    local_gender_file="$local_gender_stem.gz"

    if ! filled "$local_gender_file"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_gender_file ]]" && echo "OK" ) ]]; then
	    mkdir -p $(dirname "$local_gender_file") && \
	    scp "$remote_host":"$remote_gender_file" "$local_gender_stem.txt.COPYING.TMP"
	    mv "$local_gender_stem.txt.COPYING.TMP" "$local_gender_stem.txt" && \
	    cat "$local_gender_stem.txt" | viatmp -gz "$local_gender_file" && \
	    rm "$local_gender_stem.txt"
	    chk "$local_gender_file" "Copyed file" "-s" "was copyed" nop || exit 2
	fi
    fi
    
    # age:
    remote_age_file="$remote_age_dir/$day/predict_gr_v2.gz"
    local_age_file="$local_dir/$day/predict_gr_v2.gz"

    if ! filled "$local_age_file"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_age_file ]]" && echo "OK" ) ]]; then
	    mkdir -p $(dirname "$local_age_file")
	    scp "$remote_host":"$remote_age_file" "$local_age_file.COPYING.TMP"
	    mv "$local_age_file.COPYING.TMP" "$local_age_file"
	    chk "$local_age_file" "Copyed file" "-s" "was copyed" nop || exit 2
	fi
    fi    

    # ctr10 (Kristina's groups):
    remote_kris_file_10="$remote_kris_dir/traits$day.gz"
    local_kris_file_10="$local_dir/$day/ctr10gr.gz"
    
    if ! filled "$local_kris_file_10"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_kris_file_10 ]]" && echo OK ) ]];then
	    mkdir -p $(dirname "$local_kris_file_10")
	    scp "$remote_host":"$remote_kris_file_10" "$local_kris_file_10.TMP" 
	    mv "$local_kris_file_10.TMP" "$local_kris_file_10"
	    chk "$local_kris_file_10" "Copyed file" "-s" "was copyed" nop || exit 2
	fi
    fi
    
    # ctr11 (Kristina's 11-th group):
    remote_kris_file_11="$remote_kris_dir/inactiveUsers$day.gz"
    local_kris_file_11="$local_dir/$day/ctr11gr.gz"
    
    if ! filled "$local_kris_file_11"; then
	if [[ $( ssh "$remote_host" "[[ -s $remote_kris_file_11 ]]" && echo OK ) ]];then
	    mkdir -p $(dirname "$local_kris_file_11")
	    scp "$remote_host":"$remote_kris_file_11" "$local_kris_file_11.TMP" 
	    mv "$local_kris_file_11.TMP" "$local_kris_file_11"
	    chk "$local_kris_file_11" "Copyed file" "-s" "was copyed" nop || exit 2
	fi
    fi
    
    
done

)>>"$0.log" 2>&1
