#!/usr/bin/env bash
#> пересечение uidsz.gz за 30 дней с файлами трейтов predict_add.gz, predict_gr_v2.gz, ctr10gr.gz, ctr11gr.gz
#> v2, надеемся на ускорение.

#>> gender (predict_add.gz): 
#>> format: 1480566*11
#>>  11 - 2.54 муж
#>>  12 - 2.55 жен

#>> age (predict_gr_v2.gz):
#>> format: 10000022992*1
#>>  1 - 2.56 young (12-24)
#>>  2 - 2.57 adult (25-44)
#>>  3 - 2.60 old (45+) 

#>> ctr: (ctr10gr.gz )
#>> format: 25777293644*29926*0.3*1.00247e-05*10 (see field 5)
#>> 1 - most active
#>> 10 - minumum activity 

#>> ctr11gr.gz
#>> format: 10039181520*1*0*0*0
#> all cookies in 1-st field - in 11 group (inactive )

#>> auditory.gz
#>> format:
#>> uid * group
#>> sorted: 1,1n


set -u
set +x
set -o pipefail

# Параметр 1: имя текущего uidsz.gz
srcfile=${1:?File!} # ../REESULT/.../uidsz.gz
# Параметр 2: имя результирующего файла:
resf=${2:? ResFile! }
# Параметр 3: job (напр. google)
job=${3:?Job!} # google
# парам 4: typenum:
typenum=${4:?typenum!}
# Параметр 5: глубина дней, за сколько мержить uidsz
merge_deep=${5:?Merge Deep!} # в днях (30), за сколько дней нужны uidsz.gz
# Параметр 6: основная папка файлов трейтов. 
traits_base_dir=${6:? traits base dir!}
# Параметр 7: uids_base_dir
uids_base_dir=${7:? uids_base_dir !}


day=`fn2days "$srcfile"`

gender_file="$traits_base_dir/$day/predicted_add.gz"
chk "$gender_file" "gender file" "-s" "exists" nop || exit 2

age_file="$traits_base_dir/$day/predict_gr_v2.gz"
chk "$age_file" "age file" "-s" "exists" nop || exit 2

ctr10_file="$traits_base_dir/$day/ctr10gr.gz"
chk "$ctr10_file" "ctr10file" "-s" "exists" nop || exit 2

ctr11_file="$traits_base_dir/$day/ctr11gr.gz"
chk "$ctr11_file" "ctr11file" "-s" "exists" nop || exit 2

auditory_file="$traits_base_dir/$day/auditory.gz"
chk "$auditory_file" "auditory_file" "-s" "exists" nop || exit 2

uidsz30files=`hours -d="$day" -shift=1day -n=-"$merge_deep"days -days | files "$uids_base_dir/%F/$job/$typenum/uidsz.gz"`

# должны быть все на месте:
uidsz30files=`echo "$uidsz30files" | only -all -s`
chk "$uidsz30files" "30 uidsz.gz files for merge, не хватает: $? файлов" || exit 2 

#>> мержит все uidsz за 30 дней, уникалит и подает на вход скриту

sort -m -k1,1n \
<(mergef -ff="$uidsz30files" -m -k=1,1n -k=2,2n -postfilter="uniq | awk -v'OFS=*' '{print \$0,\"sz\"}'" -stdout ) \
<(zcat $gender_file | awk -v"OFS=*" '{print $0,"gender"}') \
<(zcat $age_file | sort -T. -t\* -S333M -k1,1n | awk -v"OFS=*" '{print $0,"age"}' ) \
<(zcat $ctr10_file | cut -d* -f1,5 | sort -T. -t\* -S333M -k1,1n | awk -v"OFS=*" '{print $0,"ctr"}') \
<(zcat $ctr11_file | cut -d* -f1 | sort -T. -S333M -k1,1n | awk -v"OFS=*" '{print $0,11,"ctr"}') \
<(zcat $auditory_file | awk -F* -v"OFS=*" '{print $0,"auditory"}' ) |
perl -Mstrict -Mwarnings -MData::Dumper -e'
# uid * value * type
# 5*43527*sz
# 66*12*gender
# 66*29*sz
# 66*2*age
# 66*34*sz
# 66*56*sz
# 66*6*ctr
# 66*14*auditory
# 66*10*auditory

# распределение значений и их типов по колонкам отчета, начиная с нулевой.
my %ind = (
 all_uids => 0, # all uids counter
 gender => { 
    11=>1, #male 
    12=>2 ,#female
 },
 age => {
    1=>3, # young
    2=>4, # adult
    3=>5, # old
 },
 ctr => {
    1=>6, # max activity
    2=>7,
    3=>8,
    4=>9,
    5=>10,
    6=>11,
    7=>12,
    8=>13,
    9=>14,
    10=>15, # min activity
    11=>16, # inactive
 },
);

# номера полей и их количество для "аудиторий":
my $start_i = 17;
for ( "01".."30" ){
 $ind{ auditory }{ $_ } = $start_i++;
}

# замыкает - trash:
$ind{ trash } = $start_i; # unknown traits or values

my $uid=0; 
my @uid_sz; 
my %traits;
my %sz;
my @auditories;

$\="\n";
$,="*";

sub break_uid(){
 for my $sz ( @uid_sz ){
    $sz{ $sz }[ $ind{ all_uids } ]++;
    for my $type ( keys %traits ){
	my $value = $traits{ $type };
	$sz{ $sz }[ $ind{ $type }{ $value } || $ind{ trash } ]++;
    }
    
    for my $au_number ( @auditories ){
	$sz{ $sz }[ $ind{ auditory }{ $au_number } ]++;
    }
 }
 undef @uid_sz;
 undef %traits; 
 undef @auditories;
}

while(<>){
 chomp;
 my ($new_uid, $new_value, $new_type) = split /\*/;
 break_uid() if $new_uid != $uid;

 $uid = $new_uid;
 if ( $new_type eq "sz" ){ push @uid_sz, $new_value }
 elsif( $new_type eq "auditory" ){ push @auditories, $new_value }
 else{ $traits{ $new_type } = $new_value }
};



for my $sz ( sort {$a<=>$b} keys %sz ){
    $sz{ $sz }[ $ind{ trash } ]||=0; # чтобы пропечатать все колонки, даже пустые.
    print map {$_||0} $sz, @{ $sz{ $sz } };
}

#>> out
#>> sz * all * male * fem * age1 * age2 * age3 * ctr1 * ctr2 * ctr3 * ... ctr11 * auditory01 * aud02 * aud03 * ... auditory30 * trash
#>> 1     2      3      4     5     6      7       8     9       10         18      19           20      21            48        49
'
 



