#!/usr/bin/env bash
#> For: net / tn0 / total.gz ----( 35_process )------> dom_net.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job="net"
typenum="0"
#N=`froms 19_URLS30DAYS -var=N -strict`
days=${1:-""} # можно указать "$day1 $day2 ..."
deb=${2:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x


if [[ -n "$days" ]]; then
    ff=$( echo "$days" | files "../RESULT/10/%F/$job/$typenum/total.gz" | only -sizegt=20 )
else
    ff=$(
	find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/total.gz" | sort -r | only --without="dom_net.gz" |
	only -sizegt=20
	)
fi

maxf=`conf 00_conf.txt maxf`      
echo "$ff" | washing -maxf="$maxf" -res="s|total\.gz|dom_net.gz|" -v_flag="./35_process %s $job $typenum" -comp=gzip -time=00_all.time.log


)>>"$0.log" 2>&1
