#!/usr/bin/env bash
#> net_sites / 0 / total ----> views
set -u
set +x
set -o pipefail
cd `dirname $0`

src=${1:?src!}
job=${2:?job!}
typenum=${3:?typenum!}
#N=${4:?N!}

# format net_sites tn0 total 
# IN:
#  1    2     3  4  5  6        7           8           9        10   11    12   13    14      15
# uid second sid sz pz bt exposureprice secondprice divexpsecond ad network dom path sestart isview

zcat "$src" | awk -F\* -v'OFS=*' '{ print $3,$4,($11>0?1:0),$7,$8,$9 }' | sort -t\* -T. -S 333M -k1,1n -k2,2n -k3,3n | summator -fu="+cnt,sum,sum,sum" | 
 perl -F'\*' -lane'
 # округление десятичных во всех полях:
 print join "*", map {int($_)} @F'

#>> OUT:
#>> | field            | decr |
#>> |----------------  | ---- |   
#>> | sid              |
#>> | sz               |
#>> | is_network?      | = 1/0                       |
#>> | exposures        | сумма просмотров            |
#>> | sum_expprice     | сумма exposureprice         |
#>> | sum_secondprice  | сумма secondprice           |
#>> | sum_divexpsecond | сумма отношений exppr/secpr |
