#!/usr/bin/env bash
# ------------ !!!! -----------
#> Решил не делать - а все брать из url_total.


#> net_sites / 0 / url_total ----> url_views
set -u
set +x
set -o pipefail
cd `dirname $0`

src=${1:?src!}
job=${2:?job!}
typenum=${3:?typenum!}
#N=${4:?N!}

# format net_sites tn0 total 
# IN:
#  1    2     3    4        5             6         
# dom  path  net  cnt  sum_expprice  sum_secondprice
  
zcat "$src" | awk -F\* -v'OFS=*' '$3>0 { print $1,$2,$4,$6 }'  # <--- 1-dom  2-path  3-cnt  4-sum_secondprice

#>> OUT:
#>> | field            | decr |
#>> |----------------  | ---- |   
#>> | dom              |
#>> | path             |
#>> | exposures        | сумма просмотров            |
#>> | sum_secondprice  | сумма secondprice           |
