#!/usr/bin/env bash
#> net_sites tn0 total.gz ----(37_process)-------> views.gz 

(

set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?"job!"}

processor=`href -dict="net_sites=>1" -val="$job"`
[[ -n "$processor" ]] || exit 1

typenum="0"
#N=`froms 19_URLS30DAYS -var=N -strict`
days=${2:-""} # можно указать "$day1 $day2 ..."

variant=${3:-""} # f.e. "view"

# оставлена поддержка prefix/suffix, но не используется - url_views решил не делать.
prefix=""
suffix=""
[[ -n "$variant" ]] && prefix="${variant}_" && suffix="_${variant}"


deb=${4:-""} # можно указать "deb"

[[ -n "$deb" ]] && set -x


if [[ -n "$days" ]]; then
    ff=$( echo "$days" | files "../RESULT/10/%F/$job/$typenum/${prefix}total.gz" | only -sizegt=20 )
else
    ff=$(
	find ../RESULT/10 -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/$job/$typenum/${prefix}total.gz" | sort -r | only --without="${prefix}views.gz" |
	only -sizegt=20
	)
fi
  
maxf=`conf 00_conf.txt maxf`  
echo "$ff" | washing -maxf="$maxf" -res="s|${prefix}total\.gz|${prefix}views.gz|" -v_flag="./37_process${suffix} %s $job $typenum" -comp=gzip -time=00_all.time.log


)>>"$0.log" 2>&1
