#!/usr/bin/env bash
#> Объединение сумм из отдельных: bids.gz, tn0/.../total.gz, tn1/.../total.gz, sessions.gz
#>  в одну таблицу по sz + ad.
#> за 30 дней
set -u
set +x
set -o pipefail

#> Этот скрипт только для google, ssp_sites.

bids_fn=${1:?src_file!} 
job=${2:?job!}
typenum=${3:?typenum!}
deb=${4:-""}

[[ -n "$deb" ]] && set -x

day=`fn2days "$bids_fn"`
days=`hours -d="$day" -shift=1day -n=-30days -days`

# для каждой таблицы по 30 дней назад (включая рассчетный), с проверкой существования:
bids_ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/bids.gz" | only -all -s`
chk "$bids_ff" "30 файлов bids.gz (не хватает $?)" || exit 3

tn0_total_ff=`echo "$days" | files "../RESULT/10/%F/$job/0/total.gz" | only -all -s`
chk "$tn0_total_ff" "30 файлов показов (не хватает $?)" || exit 3

tn1_total_ff=`echo "$days" | files "../RESULT/10/%F/$job/1/total.gz" | only -all -s`
chk "$tn1_total_ff" "30 файлов кликов (не хватает $?)" || exit 3

sessions_ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/sessions.gz" | only -all -s`
chk "$sessions_ff" "30 файлов sessions.gz (не хватает $?)" || exit 3

pzbt_ff=`echo "$days" | files "../RESULT/10/%F/$job/$typenum/pzbt.gz" | only -all -s`
chk "$pzbt_ff" "30 файлов pzbt.gz (не хватает $?)" || exit 3

# а так же 1 файл traits30days.gz (в нем уже 30 дней)
traits_fn=`echo "$day" | files "../RESULT/10/%F/$job/$typenum/traits30days.gz" | only -all -s`
chk "$traits_fn" "($0, line: $LINENO) traits30days.gz за $day" || exit 3

# Порядок сетей в отчете:
nets="net-forty-three net-forty-four net-forty-five net-sixty"

# Чтобы получить список сетей в которые входит сайтзона
dom_net_ff=`echo "$days" | files "../RESULT/10/%F/net_sites/0/dom_net.gz" | only -all -s`
not_found_ff=""
[[ -z "$dom_net_ff" ]] && not_found_ff=`echo "$days" | files "../RESULT/10/%F/net_sites/0/dom_net.gz" | only "[[ ! -s %f ]]"`
chk "$dom_net_ff" "dom_net.gz for 30 days (не хватает: $not_found_ff)" || exit 3 

# текущий dom_gr:
dom_gr_f=`echo "$day" | files "../RESULT/10/%F/$job/$typenum/dom_gr.txt" | only -all -s`
chk "$dom_gr_f" "1 файл dom_gr ../RESULT/10/%F/$job/$typenum/dom_gr.txt " || exit 3

# аудитории Ильи (auditory.gz), 
auditory_f="./auditory.gz"
scp dm8.adriver.x:/usr/local/rle/var/share3/DATA/all_sites_10p_traffic/auditory.gz ./
chk "$auditory_f" "файл аудиторий" '-s $_' 'exists' noprint || exit 3  

#> смерженные файлы bids.gz:
#> 30 days bids.gz мержатся по первым двум полям (sz,ad), третье поле (bids_count) суммируется, четвертое (dom) - берется последнее значение по данному ключу:
#> (ad нужна для posi_bids - ни равны 0 при ad==0)
mergef -ff="$bids_ff" -m -k=1,1n -k=2,2n -stdout | summator -fu="sum,last" |
awk -F* -v"OFS=*" '
# здесь сворачиваем строки по sz, добавляя positive_bids
# INPUT:
# sz ad bids dom
{
 if($1 != sz) flush();
 sz=$1;
 bids+=$3;
 if ($2!=0) posibids+=$3;
 dom=$4;
}
END{
 flush();
}

function flush(){
 if (sz){
    print sz,bids,posibids,dom
 }
 bids=0; posibids=0;
}
# OUT:
# sz, all_bids, positive_bids, dom
# ------------------------------------
' | lae -lb="sz bids posibids dom" '
# Объединение входных строк по sz с другими таблицами.

my %co = do "00_conf.txt";

my $net_list = shift or die "nets!";
my @net_list = grep {$_} split /\s+/, $net_list;

my %vars;

# views:
open FILE, shift or die $!;
while(<FILE>){
 chomp;
 my ($sz, $exposures, $expprice, $winprice, $exp_div_win) = split /\*/, $_, -1; # поле $exp_div_win = exposure_price, деленное на winprice
 $vars{ $sz } = { exposures => $exposures, expprice => $expprice, winprice => $winprice, exp_div_win=>$exp_div_win };
}

# clicks:
open FILE, shift or die $!;
while(<FILE>){
 chomp;
 my ($sz, $clicks) = split /\*/, $_, -1;
 $vars{ $sz }{ clicks } = $clicks;
}

# sessions:
my %sessions;
open FILE, shift or die $!;
while(<FILE>){
 chomp;
 my ($dom, $sess_cnt, $views) = split /\*/, $_, -1;
 $sessions{ $dom } = { sessions_count => $sess_cnt, views => $views };
}

# pzbt:
open FILE, shift or die $!;
while(<FILE>){
 chomp;
 my ($sz, $pzbt_count) = split /\*/, $_, -1;
 $vars{ $sz }{ pzbt_count } = $pzbt_count;
}

my %minimum_by_index = map { $_, 50 } 0..15; # ограничения по умолч. (=50) на мин. количво кук на сайтзоне для полей трейтов
@minimum_by_index{ 0 , 1 } = ( 30, 30 ); # male, female = 30

# traits:
#> sz * all * male * fem * age1 * age2 * age3 * ctr1 * ctr2 * ctr3 * ... ctr11 * auditory01 * aud02 * aud03 * ... auditory30 * trash
#> 1     2      3      4     5     6      7       8     9       10         18      19           20      21            48        49
#> после splita:0      1     2     3  .....  45(auditory30 ) 46(trash)

my %traits;
open FILE, shift or die $!;
while(<FILE>){
 chomp;
 my ( $sz, $cnt_on_sz, @in_traits ) = split /\*/;
 next if !$cnt_on_sz;

 $traits{ $sz } = [ $cnt_on_sz ];
 # количество колонок в отчете д.б. постоянно, поэтому оперируем постоянным набором индексов: 
 # последнюю колонку (trash) - не включаем в отчет.
 for my $i ( 0 .. 45 ){
    my $cnt_in_trait = $in_traits[$i]; # кол-во кук в трейте
    push @{ $traits{ $sz } }, 
	$cnt_on_sz >= $minimum_by_index{ $i } ?
	    sprintf( "%.2f", $cnt_in_trait * 100 / $cnt_on_sz) :
	    "NA";
 }
}

# all nets views:
my %all_net_views;
open FILE, shift or die $!;
while(<FILE>){
 chomp;
 my ($dom, $net) = split /\*/;
 $all_net_views{ $dom }{ $net }||=1;
}
die "Hash all_net_views is empty. Possible file(s) for all nets from 30 days typenum=tn0 is empty?" if !%all_net_views;



# список интересуемых PZ-он:
my @pz_list = @{ $co{pz} } or die "pz!"; 

# суммы бидов по pz:
my $pz_file = shift or die "pz_file!";
open FILE, $pz_file or die "cant open $pz_file: $!";
my %pz_bids;
while(<FILE>){
 chomp;
 my ($sz, $pz, $cnt) = split /\*/, $_, -1;
 $pz_bids{ $sz }{ $pz } = $cnt;
}

# список интересуемых BT-пов:
my @bt_list = @{ $co{bt} } or die "bt!";

#суммы бидов по bt:
my $bt_file = shift or die "bt_file!";
open FILE, $bt_file or die "cant open %bt_file: $:";
my %bt_bids;
while(<FILE>){
 chomp;
 my ($sz, $bt, $cnt) = split /\*/, $_, -1;
 $bt_bids{ $sz }{ $bt } = $cnt;
}

# группы доменов из dom_gr:
my $dom_gr = shift or die "dom_gr file!";
open FILE, $dom_gr or die cant open $dom_gr: $!";
my %dom_gr;
while(<FILE>){
 chomp;
 my ($dom, $gr) = split /\*/, $_, -1;
 $dom_gr{ $dom } = $gr;
}

# Аудитории Ильи (auditory.gz)
my $audit_file = shift or die "auditory file!";
open FILE, $audit_file or die "cant open $audit_file: $!";
my %auditory_number;
while(<FILE>){
 chomp;
 my ($dom, $aud_num) = split /\*/, $_, -1;
}


$|=1;
_{
 # in:
 # sz, bids, posibids, dom
 
 my $vars_sz = $vars{ $F[SZ] }||{};
 
 my ( $ctr, $avg_winprice, $avg_exp_div_win );
 if ( my $exposures = $vars_sz->{exposures} ){
    if ( $F[BIDS]>=1000 && $vars_sz->{clicks} && $exposures>=100 or $exposures>=1000 ){
	$ctr = sprintf( "%.6f", ($vars_sz->{clicks}||0) / $exposures );
    }else{ 
	$ctr = "NA" 
    }	
    if ( $exposures>=50 ){
	$avg_winprice = sprintf( "%.4f", ( $vars_sz->{ winprice }||0 ) / $exposures);
	$avg_exp_div_win = sprintf( "%.4f", $vars_sz->{ exp_div_win } / $exposures );
    }else{
	$avg_winprice = "NA";
	$avg_exp_div_win = "NA";
    }	
 }else{
    $ctr = "NA";
    $avg_winprice = "NA";
    $avg_exp_div_win = "NA";
 }
 
 my $winbids =  $F[BIDS]>=200 ?
    sprintf("%.2f", ($vars_sz->{exposures}||0) / $F[BIDS] * 100 ) :
    "NA";

 my $traits_sz = $traits{ $F[SZ] }||[];

 my $all_uids = $traits_sz->[0]||"NA";

 my $avg_session = $all_uids >= 30 && $F[BIDS] >= 500 && $sessions{ $F[DOM] } && $sessions{ $F[DOM] }{sessions_count} ?
    sprintf("%.2f" ,($sessions{ $F[DOM] }{views}||0) / $sessions{ $F[DOM] }{sessions_count} ) :
    "NA";
 
 my $posibids = $F[BIDS] >= 200 ?
    sprintf( "%.4f", ($F[POSIBIDS]||0) / $F[BIDS] ) :
    "NA";   
    
 my $win_posi_bids = $F[POSIBIDS] >= 100 ?
    sprintf("%.4f", ( $vars_sz->{exposures}||0 ) / $F[POSIBIDS] ) :
    "NA"; 
 
 # список сетей, в кот входит сайтзона:
 my @in_nets = $all_net_views{ $F[DOM] } ?
    map { $all_net_views{ $F[DOM] }{ $_ } || 0 } @net_list :
    map {0} @net_list;

 my $pzbt_count = $F[BIDS] >= 100 ?
    $vars_sz->{pzbt_count} :
    "NA";    

 # процент бидов по sz,pz:  @{ $pz_bids{ $F[SZ] } } / к бидам по sz: $F[BIDS]
 
 my @pz_bids = $F[BIDS] 
    ?
    map { 
	sprintf( "%.2f", ($_||0) / $F[BIDS] * 100 ) 
    } @{ $pz_bids{ $F[SZ] } }{ @pz_list } 
    :
    map {0} @pz_list;

 my @bt_bids = $F[BIDS] 
    ?
    map {
	sprintf( "%.2f", ($_||0) / $F[BIDS] * 100 ) 
    } @{ $bt_bids{ $F[SZ] } }{ @bt_list }
    :
    map {0} @bt_list;

# die Dumper \@F, \@pz_list, \@pz_bids, \@bt_list, \@bt_bids if $F[SZ]==21;    

 my $dom_gr = $dom_gr{ $F[DOM] }||"NA";

die;
 my $auditory_number = $auditory_number{ $F[DOM] }||"NA";
 
 p0 $F[SZ], $F[DOM], $ctr, $winbids, $avg_session, $all_uids, $avg_winprice, $avg_exp_div_win, $posibids, $win_posi_bids, $pzbt_count, @in_nets,
  @{$traits_sz}[1..46], @pz_bids, @bt_bids;

 #>> OUT:
 #>> | field               | description  |
 #>> | ------------------- | ------------ |
 #>> | 1  sz               | 
 #>> | 2  domain           | 
 #>> | 3  dom_gr	   | группа домена |
 #>> | 4  ctr              | клики/показы  |
 #>> | 5  winbids          | процент выигранных нами бидов (просмотры/биды) (%) |
 #>> | 6  avg_session      | ср длина пользов. сессии на домене                 |
 #>> | 7  all_uids         | вего кук на сайтзоне                               |
 #>> | 8  avg_winprice     | средний winprice                                   |
 #>> | 9  avg_exp_div_win  | среднее отношение expprice/winprice                |
 #>> | 10  posibids        | отношение posibids/bids - доля бидов с положит ставкой  |
 #>> | 11  win_posi_bids   | доля выигранных бидов от тех, где ставка>0              |
 #>> | 12 pzbt_count       | количество сочетаний bt-pz                              |
 #>> | 13..16 in_nets      | 4 поля признаков сетей, в кот. входит сайтзона 1/0      |
 #>> | 17..62 trait fields | 46 полей: 17.male,18.female,19.young,20.adult,21.old, 22.ctr1 ... 32.ctr11, 33.auditory1 ... 62.auditory30 (in %) | 
 #>> | 63..64 pz bids      | 2 поля: процент бидов по pz / к бидам по sz в (%), список pz - в 00_conf.txt  |
 #>> | 65..79 bt bids      | 15 полей: процент бидов по bt / к бидам по sz в (%)                             |
 
};

' "$nets" <(
# ПРОСМОТРЫ за 30 дней ключ (sz,ad) (ad - потом выкидываем) , суммы по (exposures,winprice,expprice,exp_div_win):
mergef -ff="$tn0_total_ff" -m -k=1,1n -k=2,2n -stdout | cut -d* -f1,3,4,5,6 | summator -fu="sum,sum,sum,sum"
# Format: sz exposures expprice winprice exp_divided_by_win
) <(
# КЛИКИ за 30 дней ключ (sz,ad) (ad - потом выкидываем) , суммы по (clicks):
mergef -ff="$tn1_total_ff" -m -k=1,1n -k=2,2n -stdout | cut -d* -f1,3 | summator -fu="sum"
# Format: sz clicks
) <(
# SESSIONS за 30 дней, ключ (dom), суммы по (sess_count,views):
mergef -ff="$sessions_ff" -m -k=1,1 -stdout | summator -fu="sum,sum"
# Format: dom, sess_counts, views
) <(
# PZBT за 30 дней, ключ (sz), конкатенируются pz"-"bt (комбинации pz,bt), подсчитывается количество уникальных комбинаций, out: sz * кол-во комбинаций:
mergef -ff="$pzbt_ff" -m -k=1,1n -stdout | awk -F* '{print $1"*"$2"-"$3}' | summator -fu=uniq
# Format: sz cnt
) <(
# traits30days.gz:
zcat "$traits_fn"
 # format: 
 #>> sz * all * male * fem * age1 * age2 * age3 * ctr1 * ctr2 * ctr3 * ... ctr11 * auditory01 * aud02 * aud03 * ... auditory30 * trash
 #>> 1     2      3      4     5     6      7       8     9       10         18      19           20      21            48        49
) <(
 # dom_net за 30 дней
 # dom * net
 LANG=POSIX mergef -ff="$dom_net_ff" -k=1,1 -k=2,2n -m --stdout | uniq
 # Format: dom1*net1 (sorted)
) <(
 mergef -ff="$pzbt_ff" -k=1,1n -k=2,2n -k=3,3n -stdout | lae -lb="sz pz bt cnt" '
  my %co=do"00_conf.txt"; 
  my @pz=@{$co{pz}}; 
    _{ 
	return unless grep {$_==$F[PZ]} @pz; 
	p @F[SZ,PZ,CNT]
    }
 ' | sort -t\* -n -k1,1 -k2,2 | summator -fu="sum"
) <(
 mergef -ff="$pzbt_ff" -k=1,1n -k=2,2n -k=3,3n -stdout | lae -lb="sz pz bt cnt" '
  my %co=do"00_conf.txt"; 
  my @bt=@{$co{bt}}; 
   _{ 
    return unless grep {$_==$F[BT]} @bt; 
    p @F[SZ,BT,CNT]
   }
 ' | sort -t\* -n -k1,1 -k2,2 | summator -fu="sum"
) <(
 #dom_gr.txt:
 cat $dom_gr_f
 # Format :
 # dom * group
) <(
 # auditory.gz:
 zcat "$auditory_f"
 # Format:
 # dom * property (,where property in 1..30)
)
