#!/usr/bin/env bash
#> bids.gz , totals... ----> sz_vars_30days.gz
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?JOB!}
day=${2:-""} # можно указать $day
deb=${3:-""} # можно указать "deb"
[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
    net => 0,
    google => 3,
    mail => 3,
    ssp => 3,
    " -val="$job"
)


# у разных job форматы исходных total.gz могут быть разными:
#lb=$(
# href -dict="net => 'uid second sz pz bt exposureprice secondprice divexpsecond ad network dom path sestart isview',
# "               -default='uid second sz pz bt exposureprice ad dom path sestart isview' -val="$job"
#)

    
if [[ -n "$day" ]]; then
    deep="1day"
else    
    deep=`conf 00_conf.txt report_deep`
fi

maxf=`conf 00_conf.txt maxf`

ff=`hours -t=${day:-"today"} -shift=1day -n=-"$deep" -days -r |
 files "../RESULT/10/%F/$job/$typenum/bids.gz" | only -s |
 only -without="sz_vars_30days.gz"`

[[ -z "$ff" ]] && exit 0
 
echo "$ff" | washing -maxf="$maxf" -res="s|bids.gz|sz_vars_30days.gz|" -cmd="./51_process_$job \"%s\" \"$job\" \"$typenum\" \"$deb\"" -time=00_all.time.log -comp=gzip

)>>"$0.log" 2>&1
