#!/usr/bin/env bash

# сравнивает два urlvars и делать дифф по каждой колонке
# или делает начальный дифф, где все будет INSERT

# urlvars:
# 0gdz.ru*/matematika-6-klas-merzlyak*4*2*50*4*9*0*1*30*C ( C=CURRENT )
# 0gdz.ru*/matematika-6-klas-merzlyak*4*2*50*4*9*0*1*30*P ( P=PREVIOUS )

#> Usage: 

#> 1) для получения дифа по двум файлам, нужно пустить на STDIN смерженные по dom+path их потоки, 
#>  добавив дополнительную колонку к каждому потоку: "P" - для предыдущих значений, "C" - для текущих. 
#>  например,
#>  file1=../1460/RESULT/10/2015-08-03/net_sites/0/url_vars_30days.gz
#>  file2=../1460/RESULT/10/2015-08-10/net_sites/0/url_vars_30days.gz
#>  LANG=POSIX sort -t\* -m <(zcat "$file1" | perl -lne'print $_."*P"')  <(zcat "$file2" | perl -lne'print $_."*C"') -k1,1 -k2,2 | ./52_urlvars_diff"
	    

#> 2) для получения начального дифа (для первой загрузки ) - пустить на вход поток этого файла, без добавления колонки.
#>  zcat ~/1460/RESULT/10/2015-08-03/net_sites/0/url_vars_30days.gz | ./52_urlvars_diff | head

#> Формат файлов должен соответствовать описанию ниже. Разделитель - *.
# ssp и google отличаются от net:
#       1    2         3               4          5       6       7         8      9     10                 
# net: dom  path  avg_expprice, $avg_winprice, $profit, $male, $female, $buyerss  flag  int(m/(m/f))%
#													         11            12
# ssp,google: dom  path  avg_expprice, $avg_winprice, $profit, $male, $female, $buyerss  flag  int(m/(m/f))%  winrate_x1000  exppr3

set -u
job=${1:? JOB! } # у разных job разный набор полей

#                           0   1    2     3      4     5     6      7     8    9     10     [11]      [12]                            
labels=$(href -dict="net=>'dom path exppr winpr profit male female buyers flag mfdiv version'" \
	         -default="dom path exppr winpr profit male female buyers flag mfdiv winrate exppr3 version" -value="$job" )

chk "$labels" || exit 1

lae -lb="$labels" '
# Названия полей urlvars упрощены:
# dom - домен
# path - путь
# exppr - средний expprice (ssp,google = это exppr0)
# winpr - средний winprice
# +profit - рентабельность
# +male - мальчиков
# female - девочек
# buyers - покупателей
# flag - флаг наличия данных по трейтам
# mfdiv - отношение, упрощенно, m/(m+f)
# winrate - (для google,ssp)
# exppr3 - средний exppr по всем бидам (google,ssp)
# version = "P" | "C" (prev/current)

# Note: %LI - хранит имена полей и их индексы. (dom=>0,path=>1, ... winrate=>undef или 10)

my %categs = (
 # Соответствие индексов колонок номерам категорий.
 # ( первая занята url_cat-ами )
 # не ставить "=>"!, использовать запятые
 # В левой части имена должны быть из списка, указанного в опции -lb=... (см. выше)
 $LI{buyers}, 1000,  
 $LI{male} , 1001,
 $LI{mfdiv} , 1002,
 $LI{profit} , 1003,
 $LI{exppr}, 1004,
 $LI{winpr}, 1005,
 $LI{female}, 1006,
);

$categs{ $LI{exppr3} } = 1007 if $LI{exppr3}; # Для net - это поле отсутствует
$categs{ $LI{winrate} } = 1008 if defined $LI{winrate}; # Для net - это поле отсутствует
 

my %lines;
_{
 flush() if (Path ne prevPath or Dom ne prevDom) and prevDom; 
 #> если поле Version пустое, то считается "C"-current. Для случаев когда дифф делается по одному файлу, для начальной загрузки.
 $lines{ $F[ $LI{version} ]||"C" }=[@F]; 
} -prev=>"dom,path";
flush();

sub flush{
# warn "flush called ".Dumper(\%lines);
 
 if ( exists $lines{C} ){
    my @curr = @{$lines{C}};
    for (keys %categs){
	$curr[$_]="NA" if not defined $curr[$_];
    }
    
    my $url= join "", @curr[ $LI{dom} , $LI{path} ];

    if ( not exists $lines{P} ){
	# если в текущем - есть url, а в предыдущем - нет:
	for my $ind ( keys %categs){
	    if ( $curr[$ind] ne "NA" ){
		print "$url*$categs{$ind}*$curr[$ind]*INSERT";
	    }	
	}    
    }else{
	# если есть и в текущем и в предыдущем (но могут значения в полях отличаться):
	my @prev = @{$lines{P}};
	for (keys %categs){
	    $prev[$_]="NA" if not defined $prev[$_];
	}
	for my $ind ( keys %categs){
	    #no warnings qw(uninitialized); # набор полей разный, некоторые отсутствуют
	    if ( $curr[$ind] ne $prev[$ind] ){
		# предыдущий и текущий не равны:
		if ( $curr[$ind] eq "NA" ){
		    # текущий есть NA (удаление):
		    print "$url*$categs{$ind}*$curr[$ind]*DELETE";
		}else{
		    # текущий - не NA (вставка/замена):
		    print "$url*$categs{$ind}*$curr[$ind]*INSERT"; 
		}
	    }
	}
    }
 }elsif( exists $lines{P} ){
    my @prev = @{$lines{P}}; 
    for (keys %categs){
	$prev[$_]="NA" if not defined $prev[$_];
    }    
    my $url = join "", @prev[ $LI{dom} , $LI{path} ];
    for my $ind ( keys %categs){
	next if $prev[$ind] eq "NA";
	print "$url*$categs{$ind}*$prev[$ind]*DELETE";
    }    
 }
 %lines = (); 
}
'

