#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper;
use Getopt::Long;

my $usage = q{ Usage: };

my $conf_name;

GetOptions(
 "conf=s" => \$conf_name,
 
) or die "Bad opt!";

my %conf = do $conf_name or die "$conf_name: $!";
my %decl = %{$conf{DECL}} or die "declarations!";

local $\="\n";

my $f = "site2category_all_handmade.txt";
open HM, $f or die "cant open file $f: $!";
my %hm;
while(<HM>){
 chomp;
 my ($cat, $dom, $sz, $sid) = split;
 $hm{ "$sid:$sz" } = $cat if $cat==781;
}
close HM;

#> На входе поток колонок со значениями (sz_vars), разделитель *.
while(<>){
 chomp;
 my @fields = split /\*/, $_, -1;
 my @out;
 my ($sid,$sz) = split /\:/, $fields[0];

 next if $hm{"$sid:$sz"}; # пропуск категории 781

 my $id = ( $sid << 32 ) | ($sz||0xFFFFFFFF);
 push @out, $id;
 for my $fnumber (2 .. scalar(@fields)){
    my $fdecl = $decl{ $fnumber } or next; # на выходе будут только поля, для которых есть определения в conf
    my $fvalue = $fields[$fnumber-1];
    my $rv = $fdecl->{SUB} ? &{$fdecl->{SUB}}($fvalue) : $fvalue;
    my $cat = $fdecl->{C} || $fnumber or die "C!";
    next if !$rv and !$fdecl->{Z}; # если в декларации нет Z=>1 и на выходе==0, то не спамить такое
    push @out, "$cat:$rv ($fvalue - $fdecl->{D})";
 }
 print join "*", @out;
}