#!/usr/bin/env bash
#>
#(
set -u
set +x
set -o pipefail
cd `dirname $0`

# ./55_process %s %f $server $remote_project $job $remote_script

local_srcf=${1:?Src!}
local_resf=${2:?Resf!}
server=${3:?Server!}
rem_project=${4:?Rem_proj!}
job=${5:?JOB!}
rem_script=${6:?Rem_script!}
day=`fn2days "$local_resf"`

rem_result_dir="$rem_project/RESULT/10/$job/$day"
USER=d.belyaev
rem_srcf="$rem_result_dir/$(basename $local_srcf)"
rem_out1f="$rem_result_dir/clust_sz_1.txt"
rem_out2f="$rem_result_dir/clust_sz_2.txt"
rem_out3f="$rem_result_dir/clust_sz_3.png"

# если сущ - то удаление для пересчета:
ssh "${USER}@${server}" "[[ -s $rem_srcf ]] && rm -r $rem_srcf" 
    
if ( ssh "${USER}@${server}" "mkdir -p $rem_result_dir && [[ ! -s $rem_srcf  ]]" ) ; then
    scp -p "$local_srcf" "${USER}@${server}:$rem_result_dir/"
fi    


if ( ssh "${USER}@${server}" "$rem_project/bin/clust_sz.sh $rem_srcf $rem_out1f $rem_out2f $rem_out3f" )
then
    scp "${USER}@${server}:$rem_result_dir/*.txt" "$(dirname $local_resf)"
fi    

# clear old data on $server:
ssh "${USER}@${server}" "$rem_project/bin/90_clear"

result_f=`find "$(dirname $local_resf)" -name 'clust_sz_1.txt'`
if [[ -n "$result_f" ]]; then
    exit 0
else
    echo "I'm not create clust_sz_1.txt."
    exit 1
fi        