#!/usr/bin/env bash
#> sz_vars_30days.gz -----( ...crawler job via ssh ...)----> clust_sz_1.txt
#> Запускать 1 поток!
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
day=${2:-""}
deb=${3:-""}
[[ -n "$deb" ]] && set -x

N=30
server="crawler.adriver.x"
remote_project="/work/share/d.belyaev/1460_1421"
remote_script="clust_sz.sh"
deep=`conf 00_conf.txt report_deep`

if [[ -n "$day" ]]; then
    find_path="../RESULT/10/$day/"
else
    find_path="../RESULT/10/"
fi

maxf=`conf 00_conf.txt maxf`

find "$find_path" -wholename "*/$job/3/sz_vars_${N}days.gz" | sort -r | only -upto="$deep" |
washing \
    -maxf="$maxf" \
    -res="s|sz_vars_${N}days\.gz|clust_sz_1.txt|" \
    -w="netflag --check --file=\"%f.FLAG\" -rm" \
    -r="( ! netflag --check --file=\"%f.FLAG\" -rm ) && [[ -e %f && ! -e %f.TMP ]]" \
    -do="set -o pipefail; mkdir -p %d && netflag --file=\"%f.FLAG\" -cmd=\"./55_process %s %f $server $remote_project $job $remote_script\"" \
    -time=00_all.time.log

#washing -d -res="s|doms${N}days\.gz|dom_gr.gz|" -v_flag="./21_process %s %f $server $remote_project $remote_script" -compr=gzip -time=$0.time.log 

)>>"$0.log" 2>&1


