#!/usr/bin/env bash
#> sz_vars_30days.gz -----( ...dm1 job via ssh ...)----> clust_sz_1.txt
#> Запускать 1 поток!
(
set -u
set +x
set -o pipefail
cd `dirname $0`

job=${1:?Job!}
day=${2:-""}
deb=${3:-""}
[[ -n "$deb" ]] && set -x

typenum=$(
 href -dict="
    net => 0,
    google => 3,
    mail => 3,
    ssp => 3,
    " -val="$job"
)

N=30
server="dm1.adriver.x"
remote_project="/usr/local/rle/var/share/d.belyaev/1460_1421"
remote_script="clust_sz.sh"
deep=`conf 00_conf.txt report_deep`

if [[ -n "$day" ]]; then
    find_path="../RESULT/10/$day/"
    [[ ! -d "$find_path" ]] && exit 1
    deep="366"days # отключаем deep когда day
else
    find_path="../RESULT/10/"
fi

maxf=`conf 00_conf.txt maxf`

emptyff=`find "$find_path" -wholename "*/$job/$typenum/clust_sz_1.txt" | only -sizele=0`

if [[ -n "$emptyff" ]]; then
    echo "Find and remove empty files: $emptyff. Look bugs in R-script or his source data" >&2
    rm $emptyff
fi    

find "$find_path" -wholename "*/$job/$typenum/sz_vars_${N}days.gz" | sort -r | only -upto="$deep" |
 washing \
    -maxf="$maxf" \
    -res="s|sz_vars_${N}days\.gz|clust_sz_1.txt|" \
    -w="netflag --check --file=\"%f.FLAG\" -rm" \
    -r="( ! netflag --check --file=\"%f.FLAG\" -rm ) && [[ -e %f && ! -e %f.TMP ]]" \
    -do="set -o pipefail; mkdir -p %d && netflag --file=\"%f.FLAG\" -cmd=\"./55_process %s %f $server $remote_project $job $remote_script\"" \
    -time=00_all.time.log

#washing -d -res="s|doms${N}days\.gz|dom_gr.gz|" -v_flag="./21_process %s %f $server $remote_project $remote_script" -compr=gzip -time=$0.time.log 

)>>"$0.log" 2>&1


