#!/usr/bin/env bash
#> оставляет N последних записей в логах
(
set -u
set +x
set -o pipefail
cd `dirname $0`

N=10000 # records in each log

logs=$(find . -name "*.log")
[[ -z "$logs" ]] && echo "Not found any logs.">&2 && exit 1

for log in $logs; do
    [[ "$(cat "$log" | wc -l)" -lt $N ]] && continue
    cat "$log" | tail -n$N | viatmp $log    
done

)>>"$0.log" 2>&1
