#!/usr/bin/env bash
#> Удаление пустых файлов.

export PATH=$PATH:/usr/local/rle/var/bike
export PERL5LIB=/home/d.belyaev/perl5/lib/perl5
export PATH=$PATH:/usr/local/rle/bin
export SCALA_HOME=$HOME/scala-2.11.2
export PATH=$SCALA_HOME/bin:$PATH

job=${1:?JOB!} # нужно указывать job
# следует запускать не во время работы geek , а лучше, перед его запуском

(
set -u
set +x
set -o pipefail
cd `dirname $0`

[[ -s 01_STOP_ALL.stop ]] && echo "01_STOP_ALL.stop found! Remove it and try again.">&2 && exit 1

remove_ff=`find ../RESULT/10 -wholename "*/$job/[0-3]/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9].gz" | only --sizele=20`

[[ -n "$remove_ff" ]] && echo `date +"%F %H:%M"`" Remove empty (zisele=20) files: $remove_ff">&2 && rm $remove_ff

)>>"$0.log" 2>&1
