#!/usr/bin/env bash
#> Удаление старых данных.

export PATH=$PATH:/usr/local/rle/var/bike
export PERL5LIB=/home/d.belyaev/perl5/lib/perl5
export PATH=$PATH:/usr/local/rle/bin
export SCALA_HOME=$HOME/scala-2.11.2
export PATH=$SCALA_HOME/bin:$PATH

# следует запускать не во время работы geek , а лучше, перед его запуском
force=${1:-""} # можно указать "force"
(
set -u
set +x
set -o pipefail
cd `dirname $0`

[[ -z "$force" ]] && [[ -s 01_STOP_ALL.stop ]] && echo "01_STOP_ALL.stop found! Remove it and try again.">&2 && exit 1

older="55days" # удалять старее чем

#-----часовые данные ----
jobs=`conf 00_conf.txt jobs`
typenums="0 1 3"


ff=`find ../RESULT/10/  -type d -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" |
  only -older="$older"`
  [[ -n "$ff" ]] && echo "$(date) remove $ff">&2 && rm -r $ff
  
ff=`find ../RESULT/traits_copy/  -type d -wholename "*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" |
  only -older="$older"`
  [[ -n "$ff" ]] && echo "$(date) remove $ff">&2 && rm -r $ff  


)>>"$0.log" 2>&1
